### PR TITLE
fix: Raycast from CircleHitbox's center

### LINKED ISSUE #1865: Raycast from within CircleHitbox ignores the hitbox
# Current bug behaviour
I found an issues when using CircleHitboxes and raycast. It seems that if I cast a ray from inside a circular hitbox, it automatically ignores that hitbox. But if the hitbox is replaced with a rectangular hitbox, it works fine.

# Expected behaviour
Ideally the raycast should stop at the circular hitbox similar to how it does for rectangle.

# Steps to reproduce
Here is an sample code that shows the bug.
```dart
class RayCastGame extends FlameGame with HasCollisionDetection {
  RaycastResult<ShapeHitbox>? result;
  late ShapeHitbox shapeHitbox1;
  late ShapeHitbox shapeHitbox2;

  @override
  Future<void>? onLoad() {
    debugMode = true;
    add(
      CircleComponent(
        radius: 20,
        position: size / 2,
        anchor: Anchor.center,
        paint: Paint()..color = Colors.red,
      )..add(
          shapeHitbox1 = CircleHitbox(), // Left - wrong output
          //shapeHitbox1 = RectangleHitbox(), // Right - correct output
        ),
    );

    add(
      CircleComponent(
        radius: 20,
        position: Vector2(size.x / 2, 30),
        anchor: Anchor.center,
        paint: Paint()..color = Colors.blue,
      )..add(
          shapeHitbox2 = CircleHitbox(),
        ),
    );

    return super.onLoad();
  }

  @override
  void update(double dt) {
    final ray = Ray2(
      origin: size / 2,
      direction: Vector2(0, -1),
    );

    result = collisionDetection.raycast(
      ray,
    );

    super.update(dt);
  }

  @override
  void render(Canvas canvas) {
    if (result != null) {
      canvas.drawLine(
        (size / 2).toOffset(),
        (result!.intersectionPoint)!.toOffset(),
        Paint()
          ..color = Colors.yellow
          ..strokeWidth = 5,
      );
    }
    super.render(canvas);
  }
}
```
And here are the 2 outputs when using hitbox for red circle as CircleHitbox and RectangleHitbox. Left one uses a circular hitbox and right one uses rectangular hitbox. For some reason the ray cast passes through the hitbox of red circle in first example.

image

# Flutter doctor output
```bash
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.1)
[!] Android Studio (not installed)
[√] VS Code (version 1.70.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

# More environment information
* Flame version: 1.3.0
* Platform affected: Windows (probably others too)
* Platform version affected: 11

# More information

### PR DESCRIPTION
**Pull request by ufrshubham**
# Description

When casting ray from center of a CircleHitbox, the ray didn't detect intersections with the hitbox. This was happening because of ray origin and absolute center of hitbox being coincident. When this happened, the temporary end point for the line segment used for detecting ray intersection turned out to be (0, 0). This basically meant, the ray length was zero. This PR makes sure that when such case occurs, we use the ray direction as the temporary end point.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1865 

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: packages/flame/lib/src/collisions/hitboxes/circle_hitbox.dart [hunk 1]
```diff
@@ -50,10 +50,19 @@ class CircleHitbox extends CircleComponent with ShapeHitbox {
...
-    _temporaryCenter.projection(ray.direction, out: _temporaryLineSegment.to);
-    _temporaryLineSegment.to
-      ..x *= (ray.direction.x.sign * _temporaryLineSegment.to.x.sign)
-      ..y *= (ray.direction.y.sign * _temporaryLineSegment.to.y.sign);
+
+    if (_temporaryCenter.isZero()) {
+      // If _temporaryCenter is zero, it's projection onto ray.direction
+      // will be zero. In that case, directly use ray.direction as temp
+      // end point of line segment.
+      _temporaryLineSegment.to.setFrom(ray.direction);
```
Comment (spydon) [inline packages/flame/lib/src/collisions/hitboxes/circle_hitbox.dart:58]: I don't understand how this only affected the rays going straight north, feels like it should have affected all rays cast directly from a circle center?

Comment (ufrshubham) [reply packages/flame/lib/src/collisions/hitboxes/circle_hitbox.dart:58]: Yeah, it was affecting all ray. I must have missed something when I was reporting the issue back then. But today when I tried casting rays in any direction, it was showing the same bug. Coincidence of ray origin and hitbox's center is the only condition for this to happen.

**Review by spydon — APPROVED** [review]
