### PR TITLE
fix: SpriteButtonComponent to initialize sprites in `onLoad`

### LINKED ISSUE #3293: SpriteButtonComponent throws error with button setter. (Unhandled Exception: Null check operator used on a null value)
### What happened?

I am using `SpriteButtonComponent`, with flame (v1.18.0), everything was fine, but after updating to the latest flame version (v1.19.0), I got this error :-

E/flutter ( 8758): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8758): #0      SpriteGroupComponent.updateSprite (package:flame/src/components/sprite_group_component.dart:103:13)
E/flutter ( 8758): #1      SpriteButtonComponent.button= (package:flame/src/components/input/sprite_button_component.dart:50:5)
E/flutter ( 8758): #2      DotButtonComponent.onLoad (package:pitu/pitu.dart:31:5)
E/flutter ( 8758): #3      Component._startLoading (package:flame/src/components/core/component.dart:856:26)
E/flutter ( 8758): #4      Component._addChild (package:flame/src/components/core/component.dart:606:20)
E/flutter ( 8758): #5      Component.add (package:flame/src/components/core/component.dart:568:46)
E/flutter ( 8758): #6      Pitu.onLoad (package:pitu/pitu.dart:22:5)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): #7      FlameGame.load (package:flame/src/game/flame_game.dart:105:5)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): #8      GameWidgetState.loaderFuture.<anonymous closure> (package:flame/src/game/game_widget/game_widget.dart:194:9)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): #9      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:638:31)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): 

### What do you expect?

Just expecting my code to run error free after updating flame engine `: )`
`''''`
`(oo)`
`/  \`
` ||`

### How can we reproduce this?

step 1: create a sample project in flutter. 
`flutter create <project_name>`
step 2: add/update flame latest version (v1.19.0)
`flutter pub add flame`
step 3: create a class with extends `SpriteButtonComponent` class.
step 4: in the onLoad() method, set the button setter with a `Sprite` object.
`class DotButtonComponent extends SpriteButtonComponent with HasGameReference<Pitu> {`
  `@override`
  `Future<void> onLoad() async {`
    `  position = game.size / 2;`
    `  anchor = Anchor.center;`
    `  button = Sprite(Flame.images.fromCache('dot.png'));`
    `  onPressed = () {`
      `    log("hello world");`
      `    log("Me: After all this time?");`
      `    log("Error: Always");`
    `  };`
 ` }`
`}`

step 5: run the project. (don't forget to add your component with extends SpriteButtonComponet in FlameGame)
note: if we use `SpriteButtonComponent()` Constructor and pass the `Sprite`, everything works fine.

### What steps should take to fix this?

So, after digging the error I found the issue, So the issue is in the below code :
 /// Updates the sprite for the given key.
  `void updateSprite(T key, Sprite sprite) {`
    `_sprites![key] = sprite;`
   ` _resizeToSprite();`
  `}`

this belongs to the `SpriteGroupComponent` class,
In `SpriteGroupComponent`, we set the `sprites` setter with a Map. As the `SpriteButtonComponent` extends `SpriteGroupComponent` (basically Button Component is made using Group Component), So this method is called in the `SpriteButtonComponent` class.

`set button(Sprite value) {`
    `_button = value;`
   ` updateSprite(ButtonState.up, value);`
  `}` 

And in the `updateSprite()` method, it updates the `_sprites` map, On using `SpriteButtonComponent`, the value of `_sprites` is still null because we have `button` and `buttonDown` (optional) setters we don't set `sprites` there. So it throws error. : (

### Do have an example of where the bug occurs?

_No response_

### Relevant log output

```shell
Error log: 

`E/flutter ( 8758): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8758): #0      SpriteGroupComponent.updateSprite (package:flame/src/components/sprite_group_component.dart:103:13)
E/flutter ( 8758): #1      SpriteButtonComponent.button= (package:flame/src/components/input/sprite_button_component.dart:50:5)
E/flutter ( 8758): #2      DotButtonComponent.onLoad (package:pitu/pitu.dart:31:5)
E/flutter ( 8758): #3      Component._startLoading (package:flame/src/components/core/component.dart:856:26)
E/flutter ( 8758): #4      Component._addChild (package:flame/src/components/core/component.dart:606:20)
E/flutter ( 8758): #5      Component.add (package:flame/src/components/core/component.dart:568:46)
E/flutter ( 8758): #6      Pitu.onLoad (package:pitu/pitu.dart:22:5)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): #7      FlameGame.load (package:flame/src/game/flame_game.dart:105:5)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): #8      GameWidgetState.loaderFuture.<anonymous closure> (package:flame/src/game/game_widget/game_widget.dart:194:9)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): #9      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:638:31)
E/flutter ( 8758): <asynchronous suspension>
E/flutter ( 8758): 
`
```

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.17133.1], locale en-IN)
    • Flutter version 3.24.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (12 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\BLACKSPACE\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.92.1)
    • VS Code at C:\Users\BLACKSPACE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM A336E (mobile) • RZCTA0CZP3P • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.17133.1]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 127.0.6533.101

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

### Affected platforms

All

### Other information

_No response_

### Are you interested in working on a PR for this?

- [X] I want to work on this

### PR DESCRIPTION
**Pull request by puneet-739**
# Description

Just replaced the null check operator ```!``` with null aware ```?```. 
```void updateSprite(T key, Sprite sprite) {```
```_sprites?[key] = sprite;```
``` _resizeToSprite();```
```}```
the value of ```_sprites``` set on the ```mount()``` method of the ```SpriteButtonComponent``` class

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

#3293 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/lib/src/components/sprite_group_component.dart [hunk 1]
```diff
@@ -100,7 +100,7 @@ class SpriteGroupComponent<T> extends PositionComponent
 
   /// Updates the sprite for the given key.
   void updateSprite(T key, Sprite sprite) {
-    _sprites![key] = sprite;
+    _sprites?[key] = sprite;
```
Comment (spydon) [inline packages/flame/lib/src/components/sprite_group_component.dart:103]: We should probably have an assertion here that checks that the map is initialized.

Comment (puneet-739) [reply packages/flame/lib/src/components/sprite_group_component.dart:103]: Actually, the map ```_sprites``` initialize in the ```onMount()``` method of the ```SpriteButtonComponent ``` class.

If we use the constructor ```SpriteButtonComponent()```, ```updateSprite(T key, Sprite sprite)``` method isn't used.
and if we set the ```button``` setter in the ```onLoad()``` method of the ```SpriteButtonComponet``` class, ```updateSprite(T key, Sprite sprite)``` method was called before the ```onMount()```,

So before ```_sprites``` initialization, ```_sprites![key] = sprite;```, line code was executing.
So I think assertion is not required here, as assertion is there for ```button``` and ```sprites``` of ``` SpriteButtonComponent``` and ```SpriteGroupComponent``` class in their respective ```onMount()``` method.

Comment (spydon) [reply packages/flame/lib/src/components/sprite_group_component.dart:103]: You could call `updateSprite` before `onLoad` (when you're initializing the map in there) and then it would just be skipped and the user wouldn't know, hence why the assertion is needed, so that the user can be informed that they made an unintentional no-op.

Comment (puneet-739) [reply packages/flame/lib/src/components/sprite_group_component.dart:103]: I didn't get the point how ```updateSprite``` can be called before ```onLoad``` method. 
because when we use the ```SpriteButtonComponent``` in a project and set the ```Sprite``` using ```button``` setter (in ```onLoad()``` method of our class), then the ```updateSprite``` method called. 

` set button(Sprite value) {`
  `  _button = value;`
    `updateSprite(ButtonState.up, value);`
 ` }`

and if we add assertion ```_sprites != null```, in ```updateSprite``` method, it will throw error every time, no matter ```Sprite``` is set or not (because map initialize in ```onMount()```). (tested).

So by replacing ```!```(null check) with ```?``` (null aware) operator, it will not throw error and ```_sprites``` are going to initialize in the ```onMount()``` method of the ```SpriteButtonComponent``` and assertion is doing their job in the same method. (it is working fine).

Am I missing something. : )

Comment (spydon) [reply packages/flame/lib/src/components/sprite_group_component.dart:103]: Since `updateSprite` isn't a private or `internal` method, it can be called directly by the user too, the `SpriteGroupComponent` has many more use-cases than the `SpriteButtonComponent`.
You have discovered a bug in the `SpriteButtonComponent` though, the `sprites` map should be initialized in `onLoad`, just like it says in the `onMount` assertion in `SpriteGroupComponent`.
So I'd suggest you add an assertion in `updateSprite` and move the initialization of the `sprites` map from `onMount` to `onLoad` in `SpriteButtonComponent`.

Comment (spydon) [reply packages/flame/lib/src/components/sprite_group_component.dart:104]: I fixed it up in [26514a1](https://github.com/flame-engine/flame/pull/3302/commits/26514a16bf79d4186e65cb236631374fa503f62b)

**Review by spydon — APPROVED** [review]

File: packages/flame/lib/src/components/sprite_group_component.dart (hunk 1 above)
Comment (puneet-739) [reply packages/flame/lib/src/components/sprite_group_component.dart:104]: Changes made in [26514a1](https://github.com/flame-engine/flame/pull/3302/commits/26514a16bf79d4186e65cb236631374fa503f62b) actually throws assertion `Sprites map is not yet initialized` every time when we use the `SpriteButtonComponent` class. 
Moving `sprites` map initialization from `onMount` to `onLoad` doesn't make much difference. If we consider an example 

```
class DotButtonComponent extends SpriteButtonComponent with HasGameReference<Pitu> {
  @override
  Future<void> onLoad() async {
    // super.onLoad();
    position = game.size / 2;
    anchor = Anchor.center;
    // autoResize = true;
    button = Sprite(Flame.images.fromCache('dot.png'));
    buttonDown = Sprite(Flame.images.fromCache('odd.jpg'));
    onPressed = () {
      log("Pressed");
    };
    super.onLoad();
  }
}
```
here the `button` setter will execute first (before `super.onLoad()`) and so the `updateSprite` method (will throw assertion),
So the user will not know the cause of the assertion as `Sprites` have already been set with `button` and `buttonDown` setter.

Comment (spydon) [reply packages/flame/lib/src/components/sprite_group_component.dart:104]: `super.onLoad` should always be called first in all Flame components, and since the assertion says that it should be initialized in `onLoad` it should be pretty clear to the user that they are running code before the parent's `onLoad` has run. If you have any better wording for the assertion, feel free to open a PR with it.

Comment (spydon) [reply packages/flame/lib/src/components/sprite_group_component.dart:104]: Ah, I thought I mentioned `onLoad` + the constructor in the assertion, apparently I only did that in the other assertion.

Comment (spydon) [reply packages/flame/lib/src/components/sprite_group_component.dart:104]: Clarified it even more in here:
https://github.com/flame-engine/flame/pull/3317

Comment (puneet-739) [reply packages/flame/lib/src/components/sprite_group_component.dart:104]: Actually, even if we call the `super.onLoad` before the rest of the code (especially, `button` setter), we got null check error in button setter,
```
class DotButtonComponent extends SpriteButtonComponent with HasGameReference<Pitu> {
  @override
  Future<void> onLoad() async {
    super.onLoad();
    position = game.size / 2;
    anchor = Anchor.center;
    // autoResize = true;
    button = Sprite(Flame.images.fromCache('dot.png'));
    buttonDown = Sprite(Flame.images.fromCache('odd.jpg'));
    onPressed = () {
      log("Pressed");
    };
  }
}
```
As the `onLoad` will execute first. (`SpriteButtonComponent`)
```
 @override
  void onLoad() {
    super.onLoad();
    sprites = {
      ButtonState.up: button,
      ButtonState.down: buttonDown,
    };
  }
``` 
here the `button` is not yet set. so `Sprite get button => _button!;` will throw error because `_button` is null but `!`(null check) is used here.
