### PR TITLE
fix: Step time in SpriteAnimation must be positive

### LINKED ISSUE #1372: Stucked Hot Restart/Reload
When I had stepTime property at zero my project didn't Hot Reload/Restart.
When I tried to trigger manual restart there was the message: "Reload already in progress, ignoring request".
```
 final edgeIdle = await gameRef.loadSpriteAnimation(
      'characters/edgeworth/image-022.gif',
      SpriteAnimationData.sequenced(
        amount: 1,
        stepTime: 0, // issue here I guess
        textureSize: Vector2(256, 192),
      ),
    );
```

After changing stepTime to 1 my project started to reload fine. Looks like zero value of stepTime is not correct value.

### LINKED ISSUE #1379: SpriteAnimation's function "onComplete" dont work when the animation has only one frame.
SpriteAnimation(
        [SpriteAnimationFrame(await Sprite.load('enemy3_hit.png'), 0.1)],
        loop: false)
      ..onComplete = () => current = EnemyState.normal; 

This is my code, but I have only one animation frame, the onComplete fuction dont work. Is it a bug ?

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

`SpriteAnimation` class now ensures that all animation frames have positive durations. If not, the `update()` method would go into an infinite loop.

Current constructors in SpriteAnimation converted into factory constructors so that validity checks can all be made in a single place.

Also make sure that non-looping single-frame `SpriteAnimation` works correctly and calls the `onComplete` callback after the frame ends.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- (NA) I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- (NA) I have updated/added relevant examples in `examples`.

## Breaking Change

- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1372
Closes #1379

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm!

**Review by wolfenrain — APPROVED** [review]
LGTM

File: packages/flame/test/sprite_animation_test.dart [hunk 1]
```diff
@@ -0,0 +1,61 @@
+import 'package:flame/src/sprite_animation.dart';
+import 'package:flame_test/flame_test.dart';
+import 'package:mocktail/mocktail.dart';
+import 'package:test/test.dart';
+
+void main() {
+  group('SpriteAnimation', () {
+    test('Error on empty list of frames', () {
```
Comment (erickzanardo) [inline packages/flame/test/sprite_animation_test.dart:8]:
```suggestion
    test('throws assertion error on empty list of frames', () {
```

File: packages/flame/test/sprite_animation_test.dart [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+      expect(
+        () => SpriteAnimation.spriteList([], stepTime: 1),
+        failsAssert('There must be at least one animation frame'),
+      );
+    });
+
+    test('Error on non-positive step time', () {
```
Comment (erickzanardo) [inline packages/flame/test/sprite_animation_test.dart:15]:
```suggestion
    test('throws assertion error on non-positive step time', () {
```

File: packages/flame/test/sprite_animation_test.dart [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+      expect(
+        () => SpriteAnimation.variableSpriteList(
+          [sprite, sprite, sprite],
+          stepTimes: [1, -1, 0],
+        ),
+        failsAssert('All frames must have positive durations'),
+      );
+    });
+
+    test('Error when setting non-positive step time', () {
```
Comment (erickzanardo) [inline packages/flame/test/sprite_animation_test.dart:30]:
```suggestion
    test('throws assertion error when setting non-positive step time', () {
```

**Review by erickzanardo — APPROVED** [review]
