### PR TITLE
fix: Component can now be removed in any lifecycle stage

### LINKED ISSUE #1532: Error when add and remove component while game engine paused
# Current bug behaviour

Add the component to the game after pausing engine and remove it before engine resume causes assertion fails.

# Expected behaviour
Prevent failing assertions.

# Steps to reproduce
```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame_test/flame_test.dart';

class MyGame extends FlameGame {}

final tester = FlameTester(MyGame.new);

void main() {
  tester.test('test', (game) async {
    game.pauseEngine();

    final component = Component();
    await game.add(component);
    game.remove(component);

    game.resumeEngine();
    game.update(0);
  });
}

```
# Flutter doctor output

```
✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale ko-KR)
    • Flutter version 2.10.4 at /Users/lafity101/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/lafity101/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • SM G986N (mobile)           • ...               • android-arm64  •
      Android 11 (API 30)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information
> flame version: 1.1.0

# Log information

```
'package:flame[/src/components/component.dart]()': Failed assertion: line 495 pos 12: '_state == LifecycleState.loaded || _state == LifecycleState.removed': is not true.
package:flame/…/components/component.dart:495

```

### LINKED ISSUE #1549: game frozen with assertion failed
# Current bug behaviour
 report 'Assertion failed at line 501 pos 12 of src/component/component.dart:"_state == LifecycleState.loaded || _state == LifecycleState.removed?"' ,and game frozen

# Expected behaviour
   It shound not asseet fail

# Steps to reproduce
    I do not know how to reproduce,but it occurs frequently

# Flutter doctor output

```
[✓] Flutter (Channel unknown, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/chenchao/flutter_2.8.1
    • Upstream repository unknown
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/chenchao/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /Users/chenchao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,.devops.com,localhost,local,.local
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (3 available)
    • iPhone 6s (mobile) • C5822D87-C7D1-4651-9E0C-809AF5E9C5CC • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • iPhone 12 (mobile) • AF9E9FB1-2DF3-470A-A1DC-6EFDC04383C9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.88
    ! Error: iPhone 6s cc is not connected. Xcode will continue when iPhone 6s cc is connected. (code -13)
```

# More environment information
* Flame version: 1.1.1
* Platform affected: android, ios
* Platform version affected: android 9, ios 15

# Log information

```
Assetion failed at line 501 pos 12 of src/component/component.dart:"_state == LifecycleState.loaded || _state == LifecycleState.removed?
```

# More information
if modify the method _processChildQueue() to this:
```
  void _processChildrenQueue() {
    while (_children.isNotEmpty) {
      final child = _children.first;
      if(child.parent==null) {
        print("parent is null ${child}");
        _children.removeFirst();
        break;
      };
      assert(child.parent!.isMounted);
      if (child.isLoaded&&!child.isMounted) {
        child._mount();
        _children.removeFirst();
      } else if (child._state == LifecycleState.loading) {
        break;
      } else {
        if (child._state != LifecycleState.uninitialized) {
       
          break;
        }else {
          child._load();
        }
      }
    }
  }
```
it runs well!

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

- It should now be possible to remove a component from any possible lifecycle stage.
- The `Component._state` variable converted from an enum into a bitfield in order to be able to better track the state.
- Removed restriction that components can't be added to a game from the constructor.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix.
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in dartdoc comments.
- [-] I have updated/added relevant examples in `examples`.

## Breaking Change

- [-] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1549 
Closes #1532

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: packages/flame/lib/src/components/component.dart [hunk 1]
```diff
@@ -765,28 +760,28 @@ class _LifecycleManager {
     return !(_children.isEmpty && _removals.isEmpty && _adoption.isEmpty);
   }
 
+  /// Attempt to resolve pending events in all lifecycle event queues.
+  ///
+  /// This method must be periodically invoked by the game engine, in order to
```
Comment (spydon) [inline packages/flame/lib/src/components/component.dart:765]: Periodically -> each tick?

**Review by spydon — APPROVED** [review]
Looks good! Checks are failing but I'm sure you're aware.

File: packages/flame/lib/src/components/component.dart [hunk 2]
```diff
@@ -133,6 +157,8 @@ class Component {
     removeFromParent();
   }
 
+  //#region Debug rendering
```
Comment (alestiago) [inline packages/flame/lib/src/components/component.dart:160]: What IDE are you using @st-pasha ?

File: packages/flame/lib/src/components/component.dart [hunk 3]
```diff
@@ -37,21 +36,46 @@ class Component {
...
+  ///     [onLoad] method, and can be checked via the [isLoaded] getter. Once
+  ///     set, this bit is never turned off.
+  ///
+  /// [_mounted]: this flag is set when the component becomes properly mounted
+  ///     to the component tree, and then turned off when the component is
+  ///     removed from the tree.
+  ///
+  /// [_removing]: this bit indicates that the component is scheduled for
+  ///     removal at the earliest possible opportunity, and then cleared when
+  ///     the component is actually removed.
```
Comment (alestiago) [inline packages/flame/lib/src/components/component.dart:62]: This is an awesome documentation! Great job!

Any chance we can add an example of how this changes when a component is added, changed parent, and then removed?

**Review by alestiago — COMMENTED** [review]
Nice work!

I still need to have a better dive. But overall I'm impressed on the quality of the documentation.

Having said this, I'm concerned about using bit operations. My concern is that usually Flutter developers do not perform these type of operations, hence this code can be seen as slightly more difficult to comprehend.

In addition, personally I think that it requires more thought to read bit operations since I calculate them mentally, over just reading if something is equal to something else. 

I'm thinking how can we make this code more readable, especially for beginners. 

Perhaps we can have an extension on int and have methods like `is(int value)` that checks that `this && value != 0` (mask). It would be nice to keep the performance whilst not sacrificing so much readability. Or keep the enum but have more states and map them to bits with an extension (until enhanced enums).

Also, I feel that there are many combinations that _state can have.  With no guarantee that an invalid state can be reached. Making it more error prone and difficult to maintain. Perhaps we can have a setter that, for example, checks that the state is not loaded and removed simultaneously. A possible implementation is to have the  but assertion that checks _state is always a valid state.

File: packages/flame/test/components/component_lifecycle_test.dart [hunk 4]
```diff
@@ -4,25 +4,36 @@ import 'package:flame_test/flame_test.dart';
 import 'package:flutter/widgets.dart';
 import 'package:flutter_test/flutter_test.dart';
 
-class _MyComponent extends Component {
+class LifecycleComponent extends Component {
```
Comment (alestiago) [inline packages/flame/test/components/component_lifecycle_test.dart:7]: Why public? Shouldn't this be self contained in this test file?

Comment (st-pasha) [reply packages/flame/test/components/component_lifecycle_test.dart:7]: This component is also used in the `component_test.dart`. Technically, the two test files should be combined (since we decided on a 1 test file per source file policy), but we haven't gotten to that yet. Once the files are combined, this component can be made private once again.

File: packages/flame/lib/src/components/component.dart (hunk 2 above)
Comment (st-pasha) [reply packages/flame/lib/src/components/component.dart:160]: Android Studio -- I believe Erick taught me this trick some long time ago. Does this annotation not work in any other IDE?

**Comment by spydon** [comment]
> Having said this, I'm concerned about using bit operations. My concern is that usually Flutter developers do not perform these type of operations, hence this code can be seen as slightly more difficult to comprehend.

They are only internal, I think this is a perfect use for bitfield and bit operations.
(And if someone wants to do changes to this behavior, it really isn't any rocket science to read up on how it works)

> I'm thinking how can we make this code more readable, especially for beginners.

Beginners really shouldn't be fiddling around in this part of the code. :sweat_smile: 

> Also, I feel that there are many combinations that _state can have. With no guarantee that an invalid state can be reached. Making it more error prone and difficult to maintain. Perhaps we can have a setter that, for example, checks that the state is not loaded and removed simultaneously. A possible implementation is to have the but assertion that checks _state is always a valid state.

That's a good point, but I think there are sufficient tests (and if there aren't they should be added) that ensures that a faulty state can't be reached, note again that the user isn't manipulating this field freely, but the internal state machine changes it.

File: packages/flame/lib/src/components/component.dart [hunk 5]
```diff
@@ -493,22 +517,26 @@ class Component {
...
   }
 
-  Future<void>? _load() {
+  Future<void>? _startLoading() {
+    assert(_state == _initial);
     assert(_parent != null);
-    assert(_state == LifecycleState.uninitialized);
-    _state = LifecycleState.loading;
+    assert(_parent!.findGame() != null);
+    assert(_parent!.findGame()!.hasLayout);
```
Comment (erickzanardo) [inline packages/flame/lib/src/components/component.dart:524]: We are starting to have a quite some assertions here, would it be good to have a message to give more context about them?

**Review by erickzanardo — APPROVED** [review]
I must confess that bit operations scares me a little bit (HA, get it?).

Not that I can't understand them, but they are not so human friendly, so if possible I think we could add some internal comments on the lines where the operations take place.

But even with that said, this is a nice clean up, so LGTM!!

File: packages/flame/lib/src/components/component.dart (hunk 5 above)
Comment (st-pasha) [reply packages/flame/lib/src/components/component.dart:524]: I'm trying to distinguish between assertions that trigger when the user does something wrong -- these assertions will have proper messages, -- versus the assertions that can only trigger if we did something wrong, i.e. if there is a bug in our code. The latter kind of assertions are not possible to trigger, at least we don't know how they can be possibly triggered (if we did, we'd be able to fix that). So their function is to (1) state the pre-/post-conditions of a method (for example, at a start of this method we believe that the parent is set, and that the game is laid out), and (2) guard against possible problems during future refactors.

File: packages/flame/lib/src/components/component.dart (hunk 1 above)
Comment (st-pasha) [reply packages/flame/lib/src/components/component.dart:767]: Currently we do call this method on every game tick.

But nothing stops us from calling it more or less often. For example, someone might decide to call this twice per tick - once at the beginning of update and once after the render. Or, conversely, you could decide to call this less often if the fps becomes too low.

Seems like "periodically" fits quite well to these.

**Comment by st-pasha** [comment]
Thanks for the feedback, I see there's some desire for more comments about how this all fits together, so i'll try to add those later tonight.

**Comment by alestiago** [comment]
@spydon I don't need any completer to be removed. Sorry for the confusion I meant currently we have a "loaded" completer, a "mounted" completer, but we don't have a "removed" completer.

**Comment by st-pasha** [comment]
> I was wondering if after this change we could add it.

We can, absolutely

File: packages/flame/lib/src/components/component.dart (hunk 3 above)
Comment (st-pasha) [reply packages/flame/lib/src/components/component.dart:62]: Added more detailed explanation of how state evolves over time.

File: packages/flame/lib/src/components/component.dart [hunk 6]
```diff
@@ -435,38 +550,30 @@ class Component {
...
-  /// mounted.
+  /// Removes a component from the component tree.
+  ///
+  /// This will call [onRemove] for the component and its children, but only if
+  /// there was an [onMount] call previously, i.e. when removing a component
+  /// that was properly mounted.
+  ///
+  /// A component can be removed even before it finishes mounting, however such
+  /// component cannot be added back into the tree until it at least finishes
+  /// loading.
```
Comment (spydon) [inline packages/flame/lib/src/components/component.dart:576]: Couldn't we place it straight into the loading list if it is only halfway through loading when it is re-added?

**Review by spydon — APPROVED** [review]
Excellent docs for `_state`, probably the longest one we have for a field anywhere in the whole code base.

File: packages/flame/lib/src/components/component.dart (hunk 6 above)
Comment (st-pasha) [reply packages/flame/lib/src/components/component.dart:576]: I'm worried about the case when the user is accessing `parent` from `onLoad`, and then suddenly that parent would change or become null in the middle of their code.
Of course, accessing `parent` from `onLoad` is a kind of an anti-pattern, but we have been allowing it so far, so not sure how to handle this.

We could, for example, make it an error to access `parent` while the component `isLoading` -- but that would be a breaking change, and has to be done in a separate PR, after careful consideration.

Comment (spydon) [reply packages/flame/lib/src/components/component.dart:581]: Right, I think that could be a good change so that people move such logic to `onMount` instead.
But as you said, outside of the scope of this PR then.
