### PR TITLE
Fix effects bugs, use Vector2 path for MoveEffect and generalize effects

### LINKED ISSUE #463: Cannot use CombinedEffect inside SequenceEffect
## Description

When trying to add a SequenceEffect to a PositionComponent with a CombinedEffect inside it, the following exception is thrown:

```
E/flutter (20297): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: NoSuchMethodError: The method 'toPosition' was called on null.
E/flutter (20297): Receiver: null
E/flutter (20297): Tried calling: toPosition()
E/flutter (20297): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (20297): #1      PositionComponentEffect.initialize (package:flame/effects/effects.dart:78:25)
E/flutter (20297): #2      CombinedEffect.initialize (package:flame/effects/combined_effect.dart:28:11)
E/flutter (20297): #3      CombinedEffect.reset (package:flame/effects/combined_effect.dart:62:5)
E/flutter (20297): #4      SequenceEffect.initialize.<anonymous closure> (package:flame/effects/sequence_effect.dart:33:14)
E/flutter (20297): #5      List.forEach (dart:core-patch/growable_array.dart:313:8)
E/flutter (20297): #6      SequenceEffect.initialize (package:flame/effects/sequence_effect.dart:32:13)
E/flutter (20297): #7      PositionComponent.addEffect (package:flame/components/component.dart:156:26)
```

I think the cause of this issue is quite obvious. The CombinedEffect calls initialize from the reset function, but the component parameter is null because the CombinedEffect was not initialized before with a valid component.

## Development enviroment

Flame version: 0.26.0

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.18362.1082], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

## Runtime

This issue is related to running on which platform?

 - [X] Android :android:
 - [X] iOS :apple:
 - [X] Web :browser:

I only tested this on Android and web, but I think this applies to all platforms.

## Minimal reproducible code

```dart
import 'dart:ui';

import 'package:flame/components/component.dart';
import 'package:flame/effects/combined_effect.dart';
import 'package:flame/effects/effects.dart';
import 'package:flame/game.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(MyGame().widget);
}

class MyGame extends BaseGame {

  MyGame() {
    add(MyComponent());
  }

}

class MyComponent extends PositionComponent {

  MyComponent() {
    addEffect(SequenceEffect(effects: [
      CombinedEffect(effects: []),
    ]));
  }

  @override
  void render(Canvas c) {}

}
```

### PR DESCRIPTION
**Pull request by spydon**
# Description

Fixes two effects bugs, one with the relative rotation ending in the wrong angle and one with the `CombinedEffect` resulting in NPE when using it inside a `SequenceEffect`.

Also contains:
* Generalize effects so that they can be used on all components #484 
* Use a Vector2 path for MoveEffect #482 

Fixes #463

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have added examples for new features in `doc/examples`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]
LGTM

File: doc/examples/effects/simple/lib/main_move.dart [hunk 1]
```diff
@@ -17,9 +18,19 @@ class MyGame extends BaseGame with TapDetector {
   @override
   void onTapUp(details) {
     square.addEffect(MoveEffect(
-      destination: details.localPosition.toVector2(),
+      path: [
+        details.localPosition.toVector2().clone(),
```
Comment (luanpotter) [inline doc/examples/effects/simple/lib/main_move.dart:22]: toVector creates a new clone, so clone is unnecessary. cc @erickzanardo this is how you do it.

File: doc/examples/effects/simple/lib/main_move.dart [hunk 2]
```diff
@@ -17,9 +18,19 @@ class MyGame extends BaseGame with TapDetector {
   @override
   void onTapUp(details) {
```
Comment (luanpotter) [inline doc/examples/effects/simple/lib/main_move.dart:19]: nit: Offset details

Comment (luanpotter) [reply doc/examples/effects/simple/lib/main_move.dart:19]: or rather Type details (not sure what it is)

File: lib/components/component.dart [hunk 3]
```diff
@@ -10,12 +11,18 @@ import '../extensions/vector2.dart';
...
+  /// The effects that should run on the component
+  final List<ComponentEffect> _effects = [];
+
   /// This method is called periodically by the game engine to request that your component updates itself.
   ///
   /// The time [t] in seconds (with microseconds precision provided by Flutter) since the last update cycle.
   /// This time can vary according to hardware capacity, so make sure to update your state considering this.
   /// All components on [BaseGame] are always updated by the same amount. The time each one takes to update adds up to the next update cycle.
-  void update(double t);
+  void update(double dt) {
```
Comment (luanpotter) [inline lib/components/component.dart:22]: if we are doing this, we must add @mustCallSuper here

what are the use cases? are we planning to add any non-position effects?

File: lib/components/position_component.dart [hunk 4]
```diff
@@ -203,6 +182,10 @@ abstract class PositionComponent extends Component {
     canvas.restore();
   }
 
+  @mustCallSuper
```
Comment (luanpotter) [inline lib/components/position_component.dart:185]: I think this then "inherits" must call super from the parent

File: lib/effects/combined_effect.dart [hunk 5]
```diff
@@ -16,6 +16,10 @@ class CombinedEffect extends PositionComponentEffect {
     bool isAlternating = false,
     Function onComplete,
   }) : super(isInfinite, isAlternating, onComplete: onComplete) {
+    assert(
+      effects.every((effect) => effect.component == null),
+      "No effects can be added to components from the start",
```
Comment (luanpotter) [inline lib/effects/combined_effect.dart:21]: I am a bit unclear on what this message means...

Comment (spydon) [reply lib/effects/combined_effect.dart:21]: The component has a list of effects that is added to it, but here there is a list of effects added to the effect so if it is also added to a component both the component and the CombinedEffect (or SequenceEffect) will modify the effect and it will get very unexpected behaviour.

File: lib/components/position_component.dart (hunk 4 above)
Comment (spydon) [reply lib/components/position_component.dart:185]: It should be like that, but it is currently not:
https://github.com/dart-lang/sdk/issues/35372

File: lib/components/component.dart (hunk 3 above)
Comment (spydon) [reply lib/components/component.dart:22]: Exactly, an example could be fading colors or a user could do pretty much anything with it's own implemented component.
Indeed it should have @mustCallSuper there, good catch!

File: doc/examples/effects/simple/lib/main_move.dart (hunk 2 above)
Comment (spydon) [reply doc/examples/effects/simple/lib/main_move.dart:19]: Fixed

File: doc/examples/effects/simple/lib/main_move.dart (hunk 1 above)
Comment (spydon) [reply doc/examples/effects/simple/lib/main_move.dart:22]: Fixed

File: lib/components/position_component.dart (hunk 4 above)
Comment (spydon) [reply lib/components/position_component.dart:185]: On the other hand then we have to add that to everything, I think we'll just leave out the annotation and just let them solve that bug.

Comment (luanpotter) [reply lib/components/position_component.dart]: oof. yeah I think we can keep our code clean and rely on the annotation as more as a doc until they fix that bug

File: lib/effects/combined_effect.dart (hunk 5 above)
Comment (luanpotter) [reply lib/effects/combined_effect.dart:21]: maybe something like: each effect can only be added once? I assume this is the same problem of adding the same effect normally to two distinct components right. so that might be more clear

Comment (luanpotter) [reply lib/effects/combined_effect.dart:21]: also, nit: single quotes :p

File: lib/effects/sequence_effect.dart [hunk 6]
```diff
@@ -20,15 +20,17 @@ class SequenceEffect extends PositionComponentEffect {
       effects.every((effect) => effect.component == null),
       "No effects can be added to components from the start",
     );
+    assert(
+      effects.every((effect) => !effect.isInfinite),
+      "No effects added to the sequence can be infinite",
```
Comment (luanpotter) [inline lib/effects/sequence_effect.dart:25]: single quotes!

**Review by luanpotter — APPROVED** [review]
LGTM with final nits
