### PR TITLE
fix: Unique `ComponentKey` toString

### LINKED ISSUE #3457: The toString method of different ComponentKey instances will return the same string.
### What could be improved

The toString method of different ComponentKey instances returns the same string, making it difficult to debug the issue about ComponentKey.

Run the following code:

```dart
import 'package:flame/components.dart';

void main() {
  ComponentKey keyA = ComponentKey.named('key_a');
  ComponentKey keyB = ComponentKey.named('key_b');

  print('keyA: $keyA, keyB: $keyB');
}
```

We will see:

```bash
flutter: keyA: Instance of 'ComponentKey', keyB: Instance of 'ComponentKey'
```

Would overriding the toString method to return different values be a better approach?

### Why should this be improved

Run and restart the following code:

```dart
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(GameWidget(game: MyGame()));
}

class MyGame extends FlameGame {
  @override
  void onMount() {
    super.onMount();
    world.add(Player(
      position: Vector2.all(10.0),
    ));
    world.add(Player(
      position: Vector2.zero(),
    ));
  }
}

class Player extends PositionComponent {
  static String keyName = 'player_key';

  Player({required super.position})
      : super(
          size: Vector2(100, 2),
          anchor: Anchor.center,
          key: ComponentKey.named(keyName),
        );
}
```

We will see the message following:

```bash
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building FutureBuilder<void>(dirty, state: _FutureBuilderState<void>#cf097):
Key Instance of 'ComponentKey' is already registered
'package:flame/src/components/core/component_tree_root.dart':
Failed assertion: line 172 pos 12: '!_index.containsKey(key)'
```

In a complicated project,  the information above cannot help us quickly identify which instance of `ComponentKey` was registered repeatedly.

### Risks

_No response_

### More information

The part of my pubspec.yaml for this case follow:

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0

### Other

- [ ] Are you interested in working on a PR for this?

### PR DESCRIPTION
**Pull request by spydon**
# Description

This prints the hash in `ComponentKey.toString` so that users can differentiate between keys when debugging.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #3457

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/lib/src/camera/camera_component.dart [hunk 1]
```diff
@@ -45,6 +45,7 @@ import 'package:flame/src/game/flame_game.dart';
 /// added to the viewfinder will be rendered as if they were part of the world.
 /// That is, they will be affected both by the viewport and the viewfinder.
 ///
+///
```
Comment (luanpotter) [inline packages/flame/lib/src/camera/camera_component.dart]: related?

**Review by luanpotter — APPROVED** [review]
LGTM

File: packages/flame/lib/src/camera/camera_component.dart (hunk 1 above)
Comment (spydon) [inline packages/flame/lib/src/camera/camera_component.dart]:
```suggestion
```

Comment (spydon) [reply packages/flame/lib/src/camera/camera_component.dart]: Nope 😅
