### PR TITLE
Preventing methods that don't work on web to crash the app

### LINKED ISSUE #361: Prevent methods that can't be called on web to crash the game
There are some methods, like `Flame.util.fullScreen` that catastrophically crashes the game.

I think we should or do nothing when the method is called and is web, or throw a better message.

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Please include a summary of the change.

Fixes #361 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
~~- [ ] I have added examples for new features in `doc/examples`~~
- [x] The continuous integration (CI) is passing

### CODE REVIEW

File: lib/flame_audio.dart [hunk 1]
```diff
@@ -31,13 +33,26 @@ class FlameAudio {
     return audioCache.loop(file, volume: volume);
   }
 
+  void _warnWebFecthing() {
+    print(
+        'Prefetching audio is not supported by Audiplayers on web yet, to prefetch audio on web, try using the http package to get the file and the browser will handle cache');
```
Comment (luanpotter) [inline lib/flame_audio.dart:38]: trailing comma ;)

Comment (spydon) [reply lib/flame_audio.dart:38]: Full stop would be nicer than the trailing comma. :)

Comment (erickzanardo) [reply lib/flame_audio.dart]: Done
