### PR TITLE
Fix gesture detection on children

### LINKED ISSUE #635: Nested components cannot trigger click events
## Description

Nested components cannot trigger click events

## Development environment

Flame version: ^1.0.0-rc5

Flutter doctor:

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale zh_CN.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x] Android :android:
 - [ ] iOS :apple:
 - [ ] Web :browser:

## Minimal reproducible code (Required for bugs)

Include a minimal code that reproduces the problem add it inline using code block markdown, or a link to Github repository:

### PR DESCRIPTION
**Pull request by spydon**
# Description

Since the children aren't positioned in an absolute manner their gesture detection was off, this is fixed by taking the parent into account recursively.

Fixes #635 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on the latest `master`
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

File: lib/components/position_component.dart [hunk 1]
```diff
@@ -25,6 +24,10 @@ abstract class PositionComponent extends BaseComponent {
   /// The position of this component on the screen (relative to the anchor).
   Vector2 position = Vector2.zero();
 
+  /// If the component has a [PositionComponent] as a parent it will be
+  /// added here
+  PositionComponent positionParent;
```
Comment (erickzanardo) [inline lib/components/position_component.dart:29]: This should be private to avoid people messing around with this field?

Comment (spydon) [reply lib/components/position_component.dart:29]: True, do we want a getter for it, or should we skip exposing it for now?

Comment (erickzanardo) [reply lib/components/position_component.dart:29]: Initially, this seems to internal for me to be exposed, but I wouldn't oppose a getter as well.

**Review by erickzanardo — APPROVED** [review]
LGTM, just linking this to #635 as this probably fix that issue.

File: lib/components/position_component.dart (hunk 1 above)
Comment (spydon) [reply lib/components/position_component.dart]: Yeah, let's keep it internal until the day someone finds a usecase for it.

File: lib/components/position_component.dart [hunk 2]
```diff
@@ -25,6 +24,10 @@ abstract class PositionComponent extends BaseComponent {
   /// The position of this component on the screen (relative to the anchor).
   Vector2 position = Vector2.zero();
 
+  /// If the component has a [PositionComponent] as a parent it will be
+  /// added here
```
Comment (wolfenrain) [inline lib/components/position_component.dart:28]: `it will be set here.` Would be a more accurate description :-)

**Review by wolfenrain — APPROVED** [review]
LGTM, just one nit

File: lib/components/position_component.dart (hunk 2 above)
Comment (spydon) [reply lib/components/position_component.dart]: Fixed

**Review by wolfenrain — APPROVED** [review]

File: lib/components/position_component.dart [hunk 3]
```diff
@@ -25,6 +24,9 @@ abstract class PositionComponent extends BaseComponent {
   /// The position of this component on the screen (relative to the anchor).
   Vector2 position = Vector2.zero();
 
+  /// If the component has a [PositionComponent] as a parent it will be set here
+  PositionComponent _positionParent;
```
Comment (luanpotter) [inline lib/components/position_component.dart:28]: should we just store BaseComponent parent and we can check `is Position` where it's used? having the parent can be useful for other things

**Review by luanpotter — APPROVED** [review]
LGTM with one suggestion

File: lib/components/position_component.dart (hunk 3 above)
Comment (spydon) [reply lib/components/position_component.dart:28]: That is a good idea! Maybe later we can expose a getter for the parent too.

Comment (spydon) [reply lib/components/position_component.dart]: Fixed!
