### PR TITLE
fix: Set size of viewports in `onLoad`

### LINKED ISSUE #2426: Setting `visibleGameSize` for `CameraComponent.withFixedResolution` raises `Assertion failed` exception
# Current bug behavior

The game can't run because of this exception:

image

# Expected behavior

It used to work fine on Flame 1.6.0.
If it's a breaking change, it should be documented somewhere to know how to set `visibleGameSize` correctly.

# Steps to reproduce

Minimal code to reproduce: https://zapp.run/edit/flame-zweq06qwwer0

# Flutter doctor output

```
Output of: flutter doctor -v
```

# More environment information

* Flame version: main
* Platform affected: desktop

# Log information

```
Enter log information in this code block
```

# More information

### PR DESCRIPTION
**Pull request by spydon**
# Description

#2317 removed the call to `onGameResize` before `onLoad` and since the viewports relied on that for setting their sizes you couldn't change for example the `viewfinder.visibleGameSize` before the `CameraComponent` had been mounted (since `onGameResize` is called right before `onMount`).

I'm not super happy with the solution, so I'm open to any suggestions.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2426 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/lib/src/camera/viewports/fixed_aspect_ratio_viewport.dart [hunk 1]
```diff
@@ -21,10 +21,19 @@ class FixedAspectRatioViewport extends Viewport {
 
   Rect _clipRect = Rect.zero;
 
+  @override
+  void onLoad() {
+    final canvasSize = findGame()!.canvasSize;
+    _handleResize(canvasSize);
+  }
```
Comment (ufrshubham) [inline packages/flame/lib/src/camera/viewports/fixed_aspect_ratio_viewport.dart:28]: Should `onLoad` be marked with `@mustCallSuper`. It now does something special that sub-classes might miss if they forget to call onLoad.

File: packages/flame/lib/src/camera/viewports/max_viewport.dart [hunk 2]
```diff
@@ -9,6 +9,11 @@ import 'package:vector_math/vector_math_64.dart';
 class MaxViewport extends Viewport {
   MaxViewport({super.children});
 
+  @override
+  void onLoad() {
+    size = findGame()!.canvasSize;
+  }
```
Comment (ufrshubham) [inline packages/flame/lib/src/camera/viewports/max_viewport.dart:15]: Same as previous comment.

**Review by ufrshubham — APPROVED** [review]
LGTM. Added a minor comment, but not 100% sure if `@mustCallSuper` works that way.

File: packages/flame/lib/src/camera/viewports/fixed_aspect_ratio_viewport.dart (hunk 1 above)
Comment (spydon) [reply packages/flame/lib/src/camera/viewports/fixed_aspect_ratio_viewport.dart:28]: True, good catch!

**Review by erickzanardo — APPROVED** [review]
