### PR TITLE
fix: Widgets flickering

### LINKED ISSUE #3342: NineTileBoxWidget flickers inside of AnimatedOpacity container
### What happened?

When a `NineTileBoxWidget` is placed inside an `AnimatedOpacity` and the opacity changes, it will sometimes flicker. In my project, I was able to narrow it down to the use of `NineTileBoxWidget.asset` to create the widget. Loading the image earlier and then using the `NineTileBoxWidget` constructor that directly takes the `Image` instance works around the issue, even though I'm just using the `Flame.images.load` method in my code, which is what `NineTileBoxWidget` also does internally.

I've only tested this on web. Debug/release build makes no difference. With a child widget other than `NineTileBoxWidget`, the animation flicker does not occur.

### What do you expect?

I expect smooth animations with no flickering.

### How can we reproduce this?

See sample below.

### What steps should take to fix this?

I don't know Flame or Flutter well enough to suggest a fix, sorry.

### Do have an example of where the bug occurs?

This widget reproduces the issue when `visible` is changed from `true` to `false`. The widget itself is added as an overlay in the `GameWidget` and is always active.

This was the in-game menu; I've replaced the contents with a simple `Text` for brevity.

```
class MenuOverlay extends StatefulWidget {
  const MenuOverlay({super.key});

  @override
  State<StatefulWidget> createState() {
    return MenuOverlayState();
  }
}

class MenuOverlayState extends State<MenuOverlay> {
  var _visible = true;

  bool get visible {
    return _visible;
  }

  set visible(bool value) {
    if (value == _visible) return;
    setState(() {
      _visible = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return FractionallySizedBox(
        widthFactor: 1.0,
        child: AnimatedOpacity(
            opacity: _visible ? 1.0 : 0.0,
            duration: const Duration(milliseconds: 500),
            child: Container(
                color: Colors.black,
                margin: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
                child: NineTileBoxWidget.asset(
                    path: "ui/frame_64.png",
                    tileSize: 64,
                    destTileSize: 64,
                    padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 32),
                    child: IgnorePointer(
                        ignoring: !_visible,
                        child: const Text(
                            style: TextStyle(color: Colors.white, decoration: TextDecoration.none), textAlign: TextAlign.center, "Hello, World"))))));
  }
}
```

frame_64

### flutter doctor -v

```
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale sv-SE)
    • Flutter version 3.24.3 on channel stable at D:\Dev\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Dev\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code, 64-bit edition (version 1.94.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.87

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Affected platforms

Web

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Fix the flickering in the widgets: `SpriteAnimationWidget`, `SpriteWidget` and `NineTileBoxWidget`.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #3342

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/lib/src/widgets/animation_widget.dart [hunk 1]
```diff
@@ -67,24 +67,66 @@ class SpriteAnimationWidget extends StatelessWidget {
...
+    final areFramesDifferent =
+        oldValue.frames.length != newValue.frames.length ||
+            oldValue.frames.fold(
+              false,
+              (previous, frame) {
+                final newFrame =
+                    newValue.frames[oldValue.frames.indexOf(frame)];
+
+                return frame.sprite.image != newFrame.sprite.image ||
+                    frame.sprite.src != newFrame.sprite.src;
```
Comment (spydon) [inline packages/flame/lib/src/widgets/animation_widget.dart:100]: You need to take previous into consideration here right? And then have the default of the fold `true` instead of `false`.

File: examples/lib/stories/widgets/widgets.dart [hunk 2]
```diff
@@ -21,6 +22,15 @@ void addWidgetsStories(Dashbook dashbook) {
         out the settings on the pen icon.
       ''',
     )
+    ..add(
```
Comment (wsv-accidis) [inline examples/lib/stories/widgets/widgets.dart:25]: Love that you're adding an extra example for this as well!

File: packages/flame/lib/src/widgets/animation_widget.dart (hunk 1 above)
Comment (erickzanardo) [reply packages/flame/lib/src/widgets/animation_widget.dart:100]: Duh 🤦  ofc I need! Thanks!

**Review by spydon — APPROVED** [review]
Good stuff, lgtm!

**Comment by wsv-accidis** [comment]
Thank you for the swift action on this!
