### PR TITLE
fix: SpriteAnimationWidget can now be update animation safely

### LINKED ISSUE #1697: SpriteAnimationWidget is causing error when its rebuild
# Current bug behaviour
SpriteAnimationWidget uses the `SingleTickerProviderStateMixin` but its AnimationController can be disposed and recreated on `didUpdateWidget` life cycle.
As `SingleTickerProviderStateMixin` can only create ticker once,  it should be changed to `TickerProviderStateMixin`

```dart

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building BaseFutureBuilder<SpriteAnimation>:
_InternalSpriteAnimationWidgetState is a SingleTickerProviderStateMixin but multiple tickers were created.

A SingleTickerProviderStateMixin can only be used as a TickerProvider once.

If a State is used for multiple AnimationController objects, or if it is passed to other objects and those objects might use it more than one time in total, then instead of mixing in a SingleTickerProviderStateMixin, use a regular TickerProviderStateMixin.

The relevant error-causing widget was
SpriteAnimationWidget
```
# Expected behaviour

Use TickerProviderStateMixin to be able to recreate AnimationController.

# Steps to reproduce
- Minimum reproductions on SingleTickerProviderStateMixin. it causes following.
> _HasAnimationState is a SingleTickerProviderStateMixinn but multiple tickers were created.

```dart
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHome(),
    );
  }
}

class MyHome extends StatefulWidget {
  const MyHome({Key? key}) : super(key: key);

  @override
  State<MyHome> createState() => _MyHomeState();
}

class _MyHomeState extends State<MyHome> {
  @override
  void initState() {
    Future.delayed(const Duration(seconds: 2)).then((value) => setState(() {}));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: HasAnimation(
        value: Random().nextInt(100),
      ),
    );
  }
}

class HasAnimation extends StatefulWidget {
  final int value;
  const HasAnimation({Key? key, required this.value}) : super(key: key);

  @override
  State<HasAnimation> createState() => _HasAnimationState();
}

class _HasAnimationState extends State<HasAnimation>
    with SingleTickerProviderStateMixin {
  late AnimationController animationController;

  @override
  void initState() {
    setAnimation();
    super.initState();
  }

  setAnimation() {
    animationController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 1),
    );
  }

  disposeAnimation() => animationController.dispose();

  @override
  void didUpdateWidget(covariant HasAnimation oldWidget) {
    disposeAnimation();
    setAnimation();
    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.1 21C52 darwin-arm, locale ko-KR)
    • Flutter version 3.0.1 at /Users/lafity101/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/lafity101/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

# More environment information
* Flame version: main

# More information

Are you interested in working on a PR for this? Yes

### PR DESCRIPTION
**Pull request by Hwan-seok**
# Description

Now, `SpriteAnimationWidget` could be execute `didUpdateWidget` safely.
I might think there is a better solution but could not find it.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1697 

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by spydon** [comment]
Hmm, can you explain a bit more what this change is supposed to do?
According to [this page](https://api.flutter.dev/flutter/widgets/TickerProviderStateMixin-mixin.html) we should be using the `SingleTickerProviderStateMixin` since there it only one ticker here, but I'm not very familiar with these mixins, so maybe you could explain this change a bit more?

**Comment by spydon** [comment]
Thanks for the very detailed description @Hwan-seok, that makes sense!
Can't we just re-use the animation controller, or is that no possible?

**Review by spydon — APPROVED** [review]
Lgtm, good job!

File: packages/flame/lib/src/widgets/animation_widget.dart [hunk 1]
```diff
@@ -140,17 +139,19 @@ class _InternalSpriteAnimationWidgetState
   }
 
   void _setupController() {
-    _controller?.dispose();
+    widget.animation.onComplete = _pauseAnimation;
+    _controller ??= AnimationController(vsync: this)
+      ..removeListener(_onAnimationValueChanged)
+      ..addListener(_onAnimationValueChanged);
```
Comment (wolfenrain) [inline packages/flame/lib/src/widgets/animation_widget.dart:145]: I wonder, if you use the `??=` operator, will it call the `removeListener` and `addListener` only if `_controller` was null? Or will it always call it?

Because I read this code as: If `_controller` is null assign it this object and call these methods on that object

If that is the case then this won't do what you expect it to do right?

File: packages/flame/lib/src/widgets/animation_widget.dart [hunk 2]
```diff
@@ -140,17 +139,19 @@ class _InternalSpriteAnimationWidgetState
   }
 
   void _setupController() {
-    _controller?.dispose();
+    widget.animation.onComplete = _pauseAnimation;
+    _controller ??= AnimationController(vsync: this)
+      ..removeListener(_onAnimationValueChanged)
```
Comment (spydon) [inline packages/flame/lib/src/widgets/animation_widget.dart:144]:
```suggestion
    _controller ??= AnimationController(vsync: this);
    _controller
      ..removeListener(_onAnimationValueChanged)
```
Solving @wolfenrain's concern

File: packages/flame/lib/src/widgets/animation_widget.dart (hunk 1 above)
Comment (Hwan-seok) [reply packages/flame/lib/src/widgets/animation_widget.dart:145]: You are right
It should be as follows.
```dart
(_controller ??= AnimationController(vsync: this))
      ..removeListener(_onAnimationValueChanged)
      ..addListener(_onAnimationValueChanged);
```

I am very confused about this after this review because even though the code has a bug but it works by either test or real build.

And I realized that removing and re-adding the listener doesn't needed.
`widget.animation` in `_onAnimationValueChanged` already referencing the updated animation after the lifecycle event.

Comment (Hwan-seok) [reply packages/flame/lib/src/widgets/animation_widget.dart]: I removed the `removeListener` 
Thanks for the advice! :)

**Comment by erickzanardo** [comment]
Awesome! Thanks for the contribution and for the careful explanation!

**Review by erickzanardo — APPROVED** [review]
