### PR TITLE
fix: Specify size for the SpriteWidget

### LINKED ISSUE #1575: SpriteWidget gets zero height
# Current bug behaviour
When creating a SpriteWidget in a Row, the widget gets a height of zero

# Expected behaviour
A non-zero height

# Steps to reproduce
Using the [sample code]( https://github.com/bryantgtx/zero-ht-sprite), run the program, click the button marked "Append".  Each click will add a playing card to a "hand".   The Row control above the buttons will always show five images.  There will be zero to five SpriteWidgets, with empty spaces filled by a placeholder Image widget.  After the first click, the first position in the Row will change from an Image widget to a SpriteWidget.  Note that the Image widget gets a height, but the SpriteWidget does not. 

You can use the buttons to add or remove cards, but the other buttons are really only needed for a different bug.

# Flutter doctor output
```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1645], locale en-US)
    • Flutter version 2.8.1 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\greg_000\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\greg_000\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6514223
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Users\greg_000\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\201.7846.76
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\greg_000\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1645]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 98.0.1108.62
```

# More environment information
* Flame version: 1.1.1
* Platform affected: android
* Platform version affected: android 11

# Log information
none

# More information
repo linked above

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

Set `size` property for the `SpriteWidget`

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples`.

## Breaking Change

- [-] Yes, this is a breaking change.
  - (unless user code was relying on this size being zero)
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1575

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Review by spydon — APPROVED** [review]

File: packages/flame/lib/src/widgets/sprite_widget.dart [hunk 1]
```diff
@@ -106,7 +106,10 @@ class InternalSpriteWidget extends StatelessWidget {
   @override
   Widget build(_) {
     return Container(
-      child: CustomPaint(painter: SpritePainter(sprite, anchor, angle: angle)),
+      child: CustomPaint(
+        painter: SpritePainter(sprite, anchor, angle: angle),
+        size: sprite.srcSize.toSize(),
```
Comment (erickzanardo) [inline packages/flame/lib/src/widgets/sprite_widget.dart:111]: This will prevent the user to render the sprite bigger than its original size right?

I think that a better approach here would be to use the [BoxFit](https://docs-flutter-io.firebaseapp.com/flutter/painting/BoxFit-class.html) enum. Or, maybe something like that. wdyt?

Comment (erickzanardo) [reply packages/flame/lib/src/widgets/sprite_widget.dart:111]: Yeah, I get that, but this will solve one issue, while adding a new one, where all sprite widgets will always have the size of the image. And it will be impossible to render it bigger than its original size.

So we need an alternative here.

Comment (st-pasha) [reply packages/flame/lib/src/widgets/sprite_widget.dart:111]: So, i'm looking at `RenderCustomPaint` render-box, and it says that it considers the provided size as the _preferred_ size, meaning it will attempt to find the size that is as close as possible to the given size, while still satisfying the parent's constraints. Meaning that if constrains say that minSize=maxSize=100, then that will be size of the widget regardless of what its `size` property says.

I've tried this with the SpriteWidgetExample, and it can still scale the sprite both up and down.

Comment (erickzanardo) [reply packages/flame/lib/src/widgets/sprite_widget.dart:111]: > So, i'm looking at `RenderCustomPaint` render-box, and it says that it considers the provided size as the _preferred_ size, meaning it will attempt to find the size that is as close as possible to the given size, while still satisfying the parent's constraints. Meaning that if constrains say that minSize=maxSize=100, then that will be size of the widget regardless of what its `size` property says.
> 
> I've tried this with the SpriteWidgetExample, and it can still scale the sprite both up and down.

Interesting! So my concern will not happen! Thanks for checking on that. LGTM!

**Review by erickzanardo — APPROVED** [review]

**Review by wolfenrain — CHANGES_REQUESTED** [review]

File: packages/flame_test/lib/src/close_to_vector.dart [hunk 2]
```diff
@@ -2,14 +2,14 @@ import 'package:flutter_test/flutter_test.dart';
...
 ///
 /// ```dart
-/// expect(scale, closeToVector(2, -2));
-/// expect(position, closeToVector(120, 150, epsilon: 1e-10));
+/// expect(scale, closeToVector(Vector2(2, -2)));
+/// expect(position, closeToVector(expectedPosition, 1e-10));
 /// ```
-Matcher closeToVector(num x, num y, {double epsilon = 1e-15}) {
-  return _IsCloseTo(Vector2(x.toDouble(), y.toDouble()), epsilon);
+Matcher closeToVector(Vector2 vector, [double epsilon = 1e-15]) {
```
[the remark this answers is not in the document]
Comment (spydon) [reply packages/flame_test/lib/src/close_to_vector.dart]: Now the PR looks like it should again.

**Review by wolfenrain — APPROVED** [review]
