### PR TITLE
fix: Cancel taps that start inside the component and end outside

### LINKED ISSUE #3804: Tap that ends outside of component does not result in a TapCancelEvent
### What happened?

Start and end global coordinates of tap may differ slightly. If tap begins inside a component near its boundary and ends outside its boundary, the component will receive the initial TapDownEvent but will not receive the final TapUpEvent or TapCancelEvent.

### What do you expect?

When the tap is completed, the component that previously received a TapDownEvent receives a TapUpEvent or TapCancelEvent.

### How can we reproduce this?

_No response_

### What steps should take to fix this?

_No response_

### Do have an example of where the bug occurs?

The problem is easy to reproduce at least on iOS and Android.

<details>
  <summary>Example code</summary>

```dart
import 'package:flame/components.dart';
import 'package:flame/events.dart';
import 'package:flame/game.dart';
import 'package:flame/palette.dart';
import 'package:flutter/material.dart';

void main() async {
  runApp(GameWidget.controlled(gameFactory: SampleGame.new));
}

class SampleGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    final logTextComponentSize = Vector2(size.x, size.y / 2);
    final logTextPosition = Vector2(0, size.y - logTextComponentSize.y);

    final logBackground = RectangleComponent(
      paint: BasicPalette.white.paint(),
      size: logTextComponentSize,
      position: logTextPosition,
    );

    final logTextComponent = TextComponent(
      size: logTextComponentSize,
      position: logTextPosition,
      textRenderer: TextPaint(
        style: TextStyle(color: Colors.black, fontSize: 40),
      ),
    );

    final tappableComponent = TappableComponent(
      logTextComponent,
      size: Vector2(size.x / 2, size.y / 4),
      position: Vector2(size.x / 4, size.y / 8),
    );

    add(logBackground);
    add(logTextComponent);
    add(tappableComponent);
  }
}

class TappableComponent extends RectangleComponent with TapCallbacks {
  final TextComponent _logTextComponent;
  late final TextComponent _statusTextComponent;

  TappableComponent(this._logTextComponent, {super.size, super.position});

  @override
  void onLoad() {
    _statusTextComponent = TextComponent(
      textRenderer: TextPaint(
        style: TextStyle(color: Colors.black, fontSize: 40),
      ),
    );
    add(_statusTextComponent);
    _release();
  }

  void _release() {
    paint = BasicPalette.green.paint();
    _statusTextComponent.text = 'Released';
  }

  void _press() {
    paint = BasicPalette.red.paint();
    _statusTextComponent.text = 'Pressed';
  }

  @override
  void onTapDown(TapDownEvent event) {
    super.onTapDown(event);
    _press();
    _logTextComponent.text += '\nonTapDown';
  }

  @override
  void onTapUp(TapUpEvent event) {
    super.onTapUp(event);
    _release();
    _logTextComponent.text += '\nonTapUp';
  }

  @override
  void onTapCancel(TapCancelEvent event) {
    super.onTapCancel(event);
    _release();
    _logTextComponent.text += '\nonTapCancel';
  }
}
```
</details>

<details>
  <summary>Example video</summary>

https://github.com/user-attachments/assets/751f26d0-122a-494f-a955-7a82f50f6663

</details>

### Relevant log output

```shell

```

### Execute in a terminal and put output into the code block below

_No response_

### Affected platforms

All

### Other information

_No response_

### Are you interested in working on a PR for this?

- [x] I want to work on this

### PR DESCRIPTION
**Pull request by 8symbols**
# Description

Tap that starts inside the component and ends outside of it results in the usual [onTapUp call in the dispatcher](https://github.com/flame-engine/flame/blob/84fb109d2d8eb57b59055fcd3e75e514c7fb6a64/packages/flame/lib/src/events/flame_game_mixins/multi_tap_dispatcher.dart#L80-L90), but this call does not reach the component in which it started, because only the [components in which this tap ended](https://github.com/flame-engine/flame/blob/84fb109d2d8eb57b59055fcd3e75e514c7fb6a64/packages/flame/lib/src/events/messages/position_event.dart#L38-L43) are used.

These changes cancel all taps that were not successfully completed.

I guess the changes also affect the behavior of [continuePropagation](https://github.com/flame-engine/flame/blob/84fb109d2d8eb57b59055fcd3e75e514c7fb6a64/packages/flame/lib/src/events/messages/location_context_event.dart#L37-L54): if someone previously set it to false in onTapUp, other components wouldn't receive either a TapUpEvent or a TapCancelEvent. Now they will receive a TapCancelEvent. If the original behavior was truly necessary, I think it's better to separate it out into a new finish state, something like "ignored TapUp".

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Fixes #3804

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/test/events/component_mixins/tap_callbacks_test.dart [hunk 1]
```diff
@@ -153,6 +153,34 @@ void main() {
       },
     );
 
+    testWidgets(
+      'tap that starts inside the component and ends outside is cancelled',
```
Comment (spydon) [inline packages/flame/test/events/component_mixins/tap_callbacks_test.dart:157]: Can you check so that there is a test for when it is inside too and check so that it doesn't get the tap cancel when that happens? I'm guessing there already is such a test, but if not it would be good to add it.

Comment (8symbols) [reply packages/flame/test/events/component_mixins/tap_callbacks_test.dart:157]: [This test](https://github.com/8symbols/flame/blob/0ca77fb02a05724695a7e1479748b3d48718d112/packages/flame/test/events/component_mixins/tap_callbacks_test.dart#L114-L135) checks normal tap that starts and ends in the same point.

Added a symmetrical test for different points inside a component

**Comment by spydon** [comment]
Thanks for your contribution
