### PR TITLE
Fixing Tapable conflicts

### LINKED ISSUE #199: TapDectector and Tapable conflict
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-NZ)
flame: ^0.17.2

It seems that there is a conflict between TapDetector and Tapable mixins. 

If I use the TapDetector Mixin with my BaseGame class like below.

`extends BaseGame with TapDetector`

I don't see any tap events registering in my Tapable SpriteComponent. When I remove the BaseGame mixin, everything works.

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Tapable components support was causing some issues. Since it made BaseGame use the `MultiTouchTapDetector` it was preventing any other simple detector to work on BaseGame, as multi touch detectors always wins the arena over single touch detectors.

In addition to that, it caused conflicts if the user used the `MultiTouchTapDetector` mixin on the base game class, causing a lot of confusion.

Now, `Tapable` support on BaseGame is enable by the `HasTapableComponents` mixin, and it is directly hooked on the widget builder class, so no more conflicts exists, and the developer can use both `Tapable` components, and have `MultiTouchTapDetector` events on their game.

Fixes #199

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
- [x] I have added examples for new features in `doc/examples`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

File: lib/game/widget_builder.dart [hunk 1]
```diff
@@ -17,44 +18,73 @@ bool _hasBasicGestureDetectors(Game game) =>
...
+      instance
+        ..onStart = (Offset o) {
+          final drag = DragEvent();
+          drag.initialPosition = o;
+
+          game.onReceiveDrag(drag);
+
+          return drag;
+        };
+    });
```
Comment (luanpotter) [inline lib/game/widget_builder.dart:83]: missing trailing comma here

**Comment by erickzanardo** [comment]
@spydon please can you give this PR some tests on your use cases before we land it?

File: doc/input.md [hunk 2]
```diff
@@ -93,7 +95,7 @@ You can also check a more complete example [here](/doc/examples/gestures).
 
 ## Tapable components
 
-Flame also offers a simple helper to make it easier to handle tap events on `PositionComponent`. By using the mixin `Tapable` your components can override the following methods, enabling easy to use tap events on your Component.
+Flame also offers a simple helper to make it easier to handle tap events on `PositionComponent`. By added the `HasTapableComponents` mixin to your game, and using the mixin `Tapable` your components can override the following methods, enabling easy to use tap events on your Component.
```
Comment (spydon) [inline doc/input.md:98]: by adding*
on your components*
