### PR TITLE
fix!: Convert PositionEvent.canvasPosition to local coordinates

### LINKED ISSUE #2586: New Drag API: DragUpdateEvent.canvasPosition is not transformed to local coordinates
# Current bug behavior
The `canvasPosition` member variable of the `DragUpdateEvent` instance which is passed as a parameter to the `onDragUpdate` function is not transformed to local coordinates. Note that `DragStartEvent.canvasPosition` is actually transformed to local coordinate space.
With the old legacy Drag API everything works fine.

# Expected behavior
`DragUpdateEvent.canvasPosition` should be transformed to local coordinates.

# Steps to reproduce
When running a FlameGame not in fullscreen mode (e.g. with an AppBar at the Top), we can see the issue.
Example: https://zx9806jbx990.zapp.page/#/
Code:
```dart
import 'package:flutter/material.dart' hide Draggable;
import 'package:flame/components.dart';
import 'package:flame/experimental.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'package:flame/events.dart';


void main() {
  runApp(
    MaterialApp(
      home: 
        Scaffold(
          appBar: AppBar(),
          body: 
            GameWidget(
              game: MyGame(),
            ),
          
          )
      )
  );
}


class MyGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    await add(TrailDragTarget());
  }
}


class TrailDragTarget extends PositionComponent
    with DragCallbacks, HasGameRef<MyGame> {
  Trail? _trail;

  @override
  void onLoad() async {
    await super.onLoad();
    anchor = Anchor.topLeft;
    position = Vector2.zero();
    size = game.size;
  }

  @override
  void onDragStart(DragStartEvent event) {
    super.onDragStart(event);
    _trail = Trail(event.canvasPosition);
    add(_trail!);
  }

  @override
  void onDragUpdate(DragUpdateEvent event) {
    _trail?.addPoint(event.canvasPosition);
  }

  @override
  void onDragEnd(DragEndEvent event) {
    super.onDragEnd(event);
    if (_trail != null) {
      remove(_trail!);
      _trail = null;
    }
  }
}

class Trail extends Component {
  Trail(Vector2 origin)
      : _path = Path()..moveTo(origin.x, origin.y),
        _points = [origin.clone()],
        _linePaint = Paint()
          ..style = PaintingStyle.stroke
          ..color = Colors.white
          ..strokeJoin = StrokeJoin.round {
  }

  final Path _path;
  final List<Vector2> _points;
  final Paint _linePaint;

  @override
  void render(Canvas canvas) {
    _linePaint.strokeWidth = 1;
    canvas.drawPath(_path, _linePaint);
  }

  void addPoint(Vector2 point) {
    if (point.isNaN) return;
    if (_points.length > 500) return;
    if (point == _points.last) return;
    _path.lineTo(point.x, point.y);
    _points.add(point);
  }
}
```

As you can see there is a hard cut between the `canvasPosition` coordinate provided in `onDragStart` and `onDragUpdate`:
image
Expected should be a closely straight horizontal line.

# Flutter doctor output

```
Output of: flutter doctor -v
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version
    10.0.19045.2965], locale de-DE)
    • Flutter version 3.10.3 on channel stable at
      C:\Users\<redacted>\Documents\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (3 weeks ago), 2023-06-01 18:17:33
      -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[...]
```

# More environment information

* Flame version: 1.7.3
* Platform affected: web
* Platform version affected: chrome

# More information
The cause of this bug lies in the fact that the `FlameDragAdapter` simply forwards the `DragUpdateDetails` in `update` ([here](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/events/flame_drag_adapter.dart#L30)) without transforming the `DragUpdateDetails.localPosition` to local coordinate Space as it is done in `FlameDragAdapter.start` ([here](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/events/flame_drag_adapter.dart#L22)). As flutter does not provide a explicit `DragUpdateDetails.localPosition` upon construction, the `DragUpdateDetails.localPosition` variable equals the `DragUpdateDetails.globalPosition`, which is not transformed to local coordinates. 
We can either transform the `localPosition` directly inside `FlameDragAdapter.update` (which requires a reconstruction of `DragUpdateDetails` however), or don't care about the `localPosition` provided from flutter at all and use `globalPosition`/`devicePosition` for all other position variables in `PositionEvent` such as `PositionEvent.canvasPosition`. We could make `canvasPosition` late final and calculate the transformation lazy at it is done in the old legacy Drag API with `EventPosition`.

NOTE:
With the old legacy Drag API everything works fine, because the `DragUpdateDetails.localPosition` isn't even used. Only `DragUpdateDetails.globalPosition` is used to populate `EventPosition`, which in turn keeps care of all the other transformations such as `widget`, `viewport` and `game`.

### PR DESCRIPTION
**Pull request by tibotix**
# Description

This PR makes the `PositionEvent` class take a `Game` instance as a required parameter. The game is the used
to convert `canvasPosition` lazily as it is done in `EventPosition`.
As a result, i had to change several constructor calls to include the game, and make a breaking change in the `flame_test` package for all the `create[...]Events` functions. This may not be the best solution, but it is the easiest. Feel free to share your opinion and improvement ideas.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [x] Yes, this PR is a breaking change.
- [ ] No, this PR is not a breaking change.

## Migration instructions

The `create[...]Events` functions in the `flame_test` package changed their signature.
You now have to pass in the game as the required `game` named parameter.

Change:
```dart
createTapDownEvents(
    localPosition: const Offset(12, 12),
    globalPosition: const Offset(12, 12),
);
```

To:
```dart
createTapDownEvents(
    game: game,
    localPosition: const Offset(12, 12),
    globalPosition: const Offset(12, 12),
);
```

## Related Issues

Closes #2586

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/lib/src/events/messages/position_event.dart [hunk 1]
```diff
@@ -8,13 +9,15 @@ import 'package:meta/meta.dart';
...
+  PositionEvent(this._game, {required this.devicePosition});
+  final Game _game;
 
   /// Event position in the coordinate space of the game widget, i.e. relative
   /// to the game canvas.
   ///
   /// This could be considered the Flame-level global position.
-  final Vector2 canvasPosition;
+  late final Vector2 canvasPosition =
+      _game.convertGlobalToLocalCoordinate(devicePosition);
```
Comment (spydon) [inline packages/flame/lib/src/events/messages/position_event.dart:20]: Hmm, if this is used a lot it's going to be quite expensive when used in events, but I guess it already is.
Something that we should look into in the future though, how to not create so many new Vector2 objects when doing this.

**Review by spydon — APPROVED** [review]
Lgtm, thanks for your contribution!
