### PR TITLE
Preventing errors caused by the premature use of size property on game

### LINKED ISSUE #658: Component.onGameResize with zero value first call
## Description

first onGameResize on all components added to game comes with size(0.0,0.0). As consecuence, the onscreen joystick component isn't draw until next onGameResize call.

I/flutter (28817): player resize: [0.0,0.0]
I/flutter (28817): preload
I/flutter (28817): joystick resize: [0.0,0.0]
I/flutter (28817): resizing: [1280.0,844.0]
I/flutter (28817): load
I/flutter (28817): postload
I/flutter (28817): resizing: [1280.0,844.0]

## Development environment

Flame version:
  flame: ^1.0.0-rc6

Flutter doctor:

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-ES)
    • Flutter version 1.22.6 at /Users/rubenleal/Projects/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rubenleal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/rubenleal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile)    • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPad (8th generation) (mobile) • 567333F8-915B-46F6-9B11-D1BABA5DC02C • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    ! Error: iPad de Ruben is not connected. Xcode will continue when iPad de Ruben is connected. (code -13)

! Doctor found issues in 2 categories.
## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [ x] Android :android:
 - [ x] iOS :apple:
 - [ ] Web :browser:

## Minimal reproducible code (Required for bugs)

joystick demo at https://github.com/flame-engine/flame/tree/master/doc/examples/joystick

### PR DESCRIPTION
**Pull request by erickzanardo**
# Description

Flame could present weird issues when `size` or components which needed the `size` were added on the game constructor.

This PR fixes that by making a verification and failing the execution with a meaningful message.

I haven't gone through all the example to verify if all of then are working correctly to this new verification, but I think it is not worth since we are migrating all the examples.

Fixes #658

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on the latest `master`
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
- [x] I have added examples for new features in `doc/examples`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

File: lib/src/game/game.dart [hunk 1]
```diff
@@ -22,9 +22,21 @@ abstract class Game {
...
 
   /// Current game viewport size, updated every resize via the [resize] method hook
-  final Vector2 size = Vector2.zero();
+  Vector2 get size {
+    assert(hasLayout,
+        '"size" is not ready yet, did you tried to access it on the Game constructor?');
+    return _size;
+  }
+
+  final Vector2 _size = Vector2.zero();
```
Comment (luanpotter) [inline lib/src/game/game.dart:39]: it seems you have two variables to control the same thing (_size, _hasLayout)
why not start _size with null and then hasLayout := size != null?

Comment (erickzanardo) [reply lib/src/game/game.dart:39]: I would actually prefer that, but at some point we decided to not have null on that variable. I would be ok on making it billable if we all agree on that

Comment (luanpotter) [reply lib/src/game/game.dart:39]: well now that it becomes private I think it's ok, the public size getter will never return null because of the assert

Comment (wolfenrain) [reply lib/src/game/game.dart:39]: I agree, we can easily do this now!

**Review by wolfenrain — APPROVED** [review]

File: lib/src/game/base_game.dart [hunk 2]
```diff
@@ -63,7 +63,11 @@ class BaseGame extends Game with FPSCounter {
   /// Prepares and registers a component to be added on the next game tick
   ///
   /// This methods is an async operation since it await the `onLoad` method of the component. Nevertheless, this method only need to be waited to finish if by some reason, your logic needs to be sure that the component has finished loading, otherwise, this method can be called without waiting for it to finish as the BaseGame already handle the loading of the component.
+  ///
+  /// *Note:* Do not add components on the game constructor. This method can only be called after the game already has its layout set, this can be verified by the [hasLayout] property, to add components upon a game initialization, the [onLoad] method can be used instead.
   Future<void> add(Component c) async {
+    assert(hasLayout,
+        '"add" called before the game is ready, did you tried to access it on the Game constructor? Try using the "onLoad" instead');
```
Comment (spydon) [inline lib/src/game/base_game.dart:70]: tried -> try

**Review by spydon — APPROVED** [review]

File: lib/src/game/game.dart [hunk 3]
```diff
@@ -30,8 +30,24 @@ abstract class Game {
...
 
+  /// Current size of the game as provided by the framework; it will be null if not attached.
+  ///
+  /// Use [size] and [hasLayout] for safe access.
+  Vector2 _size;
+
+  /// Indicates if the this game instance had its layout layed into the GameWidget
+  /// Only this is true, the game is ready to have its size used or in the case
+  /// of a BaseGame, to receive components.
+  bool get hasLayout => size != null;
```
Comment (luanpotter) [inline lib/src/game/game.dart:41]: this got me thinking, is this the same thing as isAttached?

rn we wait for onResize which comes from the build method builder so I believe it has the actual size from `constraints.biggest`.

we could read `_gameRenderBox.size` on the onAttach method instead and then isAttached and hasLayout would be the same. however I don't think we can do that. something to study for a potential followup @erickzanardo

Comment (erickzanardo) [reply lib/src/game/game.dart:41]: Using isAttached was the first thing I tried, but it don't work as the onLoad of the game happens before the the attach method is called on game. Don't think there is much alternative to this

Comment (erickzanardo) [reply lib/src/game/game.dart:41]: Btw I noticed that you committed on the PR, this line probably should use _size instead of size

Comment (luanpotter) [reply lib/src/game/game.dart]: yep just fixed that, nice catch! took me longer than you did to find the issue

Comment (luanpotter) [reply lib/src/game/game.dart]: would be nice to have in our docs a diagram that shows the steps relating flutter steps with flame steps, like

attach -> layout -> onLoad -> game loop

and what happens/is available on each step
