### PR TITLE
Compare correct values for _transformMatrix cache

### LINKED ISSUE #854: `followComponent` appears incorrect on RC 12
On the latest RC, `1.0.0-releasecandidate.12`, the cameras `followComponent` seems to be a bit broken on sudden movement change (especially after sudden movement change, said component also remains static, as per the repro case below).

Zoom is 1, and nothing too interesting with the camera except for world bounds which only allow vertical movement.

### The pretext
I have a simple app which tracks a player component moving vertically up, with the world bounds being the world bottom, and the sides of the phone (basically doodle jump). On player death, the player will respawn at the world bottom and I expect the camera to snap to this.

### The bug
On the latest version, it appears on the player reset to the bottom of the map (this also means the player is waiting at the bottom again), that the camera does not correct snap back to the bottom.

Note: Shifting back to `1.0.0-releasecandidate.11` fixes this issue.

I have set up a fairly simple app, you can see the entire code here. You can repro this, with the `1.0.0-releasecandidate.12` version. 

This repro app features a simple textComponent that's being followed (you can see the debug stats for it's position) and it's moving up by a pixel every update tick. On pressing tap, it'll reset the position and stop moving (and the camera is called to re-follow, though I'm not even sure this should be needed). You can notice that the camera does not correctly re-center on RC12.

```
import 'dart:math';

import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/gestures.dart';
import 'package:flame/palette.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    GameWidget(game: MyGame()),
  );
}

class MyGame extends BaseGame with TapDetector {
  late final double _upperWorldCameraBound = -pow(2, 60).toDouble();

  Rect get defaultWorldBounds => Rect.fromLTRB(0, _upperWorldCameraBound, size.x, size.y);
  Vector2 get defaultTextPosition => Vector2(size.x / 2, size.y / 2);

  late final TextComponent _centerText = TextComponent(
    "Follow me",
    textRenderer: TextPaint(config: TextPaintConfig(fontSize: 28.0, fontFamily: "Baloo", color: BasicPalette.red.color)),
    position: defaultTextPosition)
    ..anchor=Anchor.center;

  late final TextComponent _positionText = TextComponent(
    '',
    textRenderer: TextPaint(config: TextPaintConfig(fontSize: 16.0, fontFamily: "Baloo", color: BasicPalette.red.color)),
    position: Vector2.all(30))
    ..anchor=Anchor.topLeft
    ..isHud=true;

  late final TextComponent _infoText = TextComponent(
    'Tap to stop moving and re-center',
    textRenderer: TextPaint(config: TextPaintConfig(fontSize: 16.0, fontFamily: "Baloo", color: BasicPalette.red.color)),
    position: Vector2(30, 60))
    ..anchor=Anchor.topLeft
    ..isHud=true;

  bool _movingUp = true;

  @override
  Future<void> onLoad() async {
    add(_centerText);
    add(_positionText);
    add(_infoText);

    camera.followComponent(_centerText, worldBounds: defaultWorldBounds);
  }

  @override
  void update(double dt) {
    super.update(dt);

    if (_movingUp) {
      _centerText.position.y -= 1;
    }

    _positionText.text = "Text pos: " + _centerText.position.toString();
  }

  @override
  void onTap() {
    _movingUp = false;
    _centerText.position = defaultTextPosition;
    camera.followComponent(_centerText, worldBounds: defaultWorldBounds);
    super.onTap();
  }
}
```

### PR DESCRIPTION
**Pull request by spydon**
# Description

This fixes the issue that was experienced when doing long jumps with the camera and the camera ended up in the wrong position.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [x] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [x] I have formatted my code with `./scripts/format.sh` and the Flame analyzer (`./scripts/analyze.sh`) does not report any problems.
- [x] I read and followed the [Flame Style Guide].
- [x] I have added a description of the change under `[next]` in `CHANGELOG.md`.
- [x] I removed the `Draft` status, by clicking on the `Ready for review` button in this PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flame users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in `CHANGELOG.md`).
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #854 

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md

### CODE REVIEW

**Review by erickzanardo — APPROVED** [review]

**Review by wolfenrain — APPROVED** [review]
LGTM

File: packages/flame/lib/src/game/camera.dart [hunk 1]
```diff
@@ -155,8 +155,8 @@ class Camera extends Projector {
     if (_transform.m11 == zoom &&
         _transform.m22 == zoom &&
         _transform.m33 == zoom &&
-        _transform.m14 == translateX &&
-        _transform.m24 == translateY) {
+        _transform.m41 == translateX &&
+        _transform.m42 == translateY) {
```
Comment (spydon) [inline packages/flame/lib/src/game/camera.dart:159]: Hmm, how does this make sense actually. (But it works...)
Do you know @wolfenrain? With `mXY` where X represents row and Y represents column this would put the values of the translation on the last row, but the translate values should be on the last column right?
```
1  0  0  tx
0  1  0  ty
0  0  1  0 
0  0  0  1
```
Where `tx` and `ty` are the translate values.
But with the changed code I'm expecting it to to check these values:
```
1  0  0  0
0  1  0  0 
0  0  1  0
tx ty 0  1

Comment (spydon) [reply packages/flame/lib/src/game/camera.dart:159]: Nvm me, it is supposed to be like the bottom matrix.

Comment (wolfenrain) [reply packages/flame/lib/src/game/camera.dart:159]: Glad I didnt had to break my brain over this haha

**Review by anleac — APPROVED** [review]
Branch fixes the issue I was experiencing - tested locally pointing at this branch 👍
