### PR TITLE
fix: Refresh vertices on size change of `RectangleComponent`

### LINKED ISSUE #1545: SizeEffect on PolygonComponent
Hi, I came across an issue while playing around with built-in effect for a small game.

# Current bug behaviour
When I use SizeEffect.to the actual effect is a move, not a resize. I had a look at the source code and tried to override it to make some test. The code is actually updating the size and the component's properties does not show anything weird so I don't really get what's going on

# Expected behaviour
Expected behaviour would be a resize of the component

# Steps to reproduce
Create a simple Game object, add a Rectangle of some size. On tap, add a SizeEffect. Minimalist source code to reproduce below :
```
class SimpleGame extends FlameGame with TapDetector {
  late Vector2 canvasSize;
  late RectangleComponent testSquare;
  @override
  void onGameResize(Vector2 size) {
    super.onGameResize(size);
    canvasSize = size;
  }

  @override
  Future<void> onLoad() async {
    testSquare = RectangleComponent(
        position: canvasSize / 2,
        size: canvasSize / 2,
        paint: BasicPalette.blue.paint(),
        anchor: Anchor.center
    );
    add(testSquare);
    await super.onLoad();
  }

  @override
  bool onTapDown(TapDownInfo event) {
    testSquare.add(SizeEffect.to(Vector2(10, 10), EffectController(duration: 1)));
    return true;
  }
}

main() {
  final game = SimpleGame();

  runApp(
    GameWidget(
      game: game,
    ),
  );
}
```

# Flutter doctor output
```
Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-x64, locale en-FR)
    • Flutter version 2.8.1 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
(...)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
```

# More environment information
* Flame version: 1.1.0
* Platform affected: ios

If needed I would be happy to work on the subject but I'm currently stuck about what to look for as the current code looks good and I can't find anything weird in my logs

### LINKED ISSUE #2166: RectangleComponent does not re-render paint after construction
# Current bug behavior
RectangleComponent doesn't re-render paint after construction

# Expected behavior
RectangleComponent does re-render paint after construction

# Steps to reproduce

Screen Shot 2022-11-13 at 8 48 43 AM

```dart
class MyGame extends FlameGame {
  final rectangle = MyRectangle();

  @override
  Future<void>? onLoad() async {
    add(rectangle);
  }
}

class MyRectangle extends RectangleComponent {
  MyRectangle() : super(size: Vector2(50, 50));

  @override
  Future<void> onLoad() async {
    size = Vector2(150, 150); // this size change doesn't re-render paint

    debugMode = true;
    position = Vector2(150, 150);
    paint = Paint()..color = Colors.green;
  }
}
```

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.7 on channel stable at /Users/lukepighetti/development/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (12 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/lukepighetti/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

# More environment information

* Flame version: 1.4.0
* Platform affected: web, perhaps more

# Log information

```
Enter log information in this code block
```

# More information

### PR DESCRIPTION
**Pull request by ufrshubham**
# Description
This PR modifies `RectangleComponent` to register a listener on `size` so that the vertices can be refreshed.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [NA] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [NA] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2166 
Partially this also fixes #1545 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: packages/flame/lib/src/geometry/rectangle_component.dart [hunk 1]
```diff
@@ -47,7 +55,11 @@ class RectangleComponent extends PolygonComponent {
           Vector2(relation.x, -relation.y),
           -relation,
           Vector2(-relation.x, relation.y),
-        ]);
+        ]) {
+    size.addListener(
```
Comment (spydon) [inline packages/flame/lib/src/geometry/rectangle_component.dart:59]: Have you tried that this works properly when it is set to relative?

**Review by spydon — APPROVED** [review]
Lgtm, some small tests would be good!

File: packages/flame/lib/src/geometry/rectangle_component.dart (hunk 1 above)
Comment (ufrshubham) [reply packages/flame/lib/src/geometry/rectangle_component.dart:59]: Not yet. I'll check all the cases and add some tests.

Comment (ufrshubham) [reply packages/flame/lib/src/geometry/rectangle_component.dart:59]: Okay, I think this will take some time. 

A quick test revealed issues with `RectangleComponent.square` as well as `RectangleComponent.relative`. So far I've only been able to figure out what is going wrong with square and here is my findings:

- Problem:
  As `size` is null while `RectangleComponent.square` is invoked, the `shrinkToBounds` flag gets set to true because of this: https://github.com/flame-engine/flame/blob/ffb36a89efdcd976fe63c16f27741b77b08aa284/packages/flame/lib/src/geometry/polygon_component.dart#L47
  When this flag is true, `PolygonComponent.refreshVertices` updates the `size` with new calculated bounds. But my fix adds a listener on `size` that calls `refreshVertices`. This causes circular calls and eventually a stack overflow.

- Solution#1
  A quick solution for this would be to explicitly set the `size` in `super()` of `RectangleComponent.square`. This does solve the problem here, but `PolygonHitbox` and `RectangleHitbox` will still suffer from this problem, where `shrinkToBounds` is explicitly set to true.

- Solution#2
  Another solution I am thinking of is to move the code that updates `size` from `refreshVertices` into a separate method. I am open for any better solution though.

Will keep investigating the problem with `relative`.

Comment (ufrshubham) [reply packages/flame/lib/src/geometry/rectangle_component.dart:65]: Fixed the `RectangleComponent.square` by overriding the `shrinkToBounds` while refreshing the vertices. For `RectangleComponent.relative` the problem was because `PolygonComponent.relative` was setting the size of component as provided `parentSize`. This was wrong and unnecessary because not setting `size` automatically calculates the size.

Comment (spydon) [reply packages/flame/lib/src/geometry/rectangle_component.dart:65]: Good job!

**Review by erickzanardo — APPROVED** [review]
