### PR TITLE
fix: Misalignment of the hittest area of PolygonHitbox

### LINKED ISSUE #2758: `HasGestureHitboxes` is slightly off
# Current bug behavior
If you try this example: https://examples.flame-engine.org/#/Input_Gesture%20Hitboxes
you can see that the hitboxes aren't perfect if you are tapping right outside some edges of polygons for example.
And also, the hover callbacks don't seem to trigger at all...
The issue was the same in v1.8.2.

# Expected behavior
That the gesture hitboxes are exact like they used to be.

# Steps to reproduce
Use this example: https://examples.flame-engine.org/#/Input_Gesture%20Hitboxes

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.13.4, on Arch Linux 6.5.3-arch1-1, locale en_DK.UTF-8)
    • Flutter version 3.13.4 on channel stable at /home/spydon/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (9 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /home/spydon/bin/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.27.5
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/spydon/bin/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.5.3-arch1-1
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

# More environment information

* Flame version: 1.8.2 and 1.9.0 at least

# More information
I'll do a git bi-sect tomorrow to find when this was introduced.

### PR DESCRIPTION
**Pull request by organic-nailer**
# Description

When performing a pointer hit test using PolygonHitbox, there may be a discrepancy between the expected range and the range in which the hit test succeeds. If the polygon shape has an offset at the top left, the hit test will behave as if there is no offset.

Investigation revealed that the cause was in the calculation of containsLocalPoint() in the PolygonComponent. The unnecessary offset calculation was removed, and the hit test is now performed in the expected range.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2758

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame/test/geometry/polygon_component_test.dart [hunk 1]
```diff
@@ -0,0 +1,40 @@
+import 'package:flame/components.dart';
+import 'package:flame/geometry.dart';
+import 'package:test/test.dart';
+
+void main() {
+  group('PolygonComponent', () {
```
Comment (spydon) [inline packages/flame/test/geometry/polygon_component_test.dart:6]: Could you move this to shape_component_test where the other tests for this are?
There are some inconsistencies of which directories the tests live currently so it can be quite hard to find the correct place. :sweat_smile:

**Review by spydon — COMMENTED** [review]
Thank you so much for looking into this! I've been meaning to look into this for months.

**Comment by spydon** [comment]
If you run `melos format` locally it should fix the formatting issue.

**Review by spydon — APPROVED** [review]
Lgtm!
