### PR TITLE
fix: Only use initialized game for tests and remove setMount from onGameResize

### LINKED ISSUE #1351: Tests should use only properly initialized game instances
Currently there are multiple tests which create a `FlameGame` instance manually and partially initialize it.

In order to reduce the amount of test breakage when the initialization process of a game changes, we should change those tests to only use a game instance acquired from properly initialized sources (such as flame_test).

### PR DESCRIPTION
**Pull request by spydon**
# Description

Since we used `setMounted` in `onGameResize` the `mounted` feature didn't work properly when invoked from for example `onLoad`. This PR makes sure that all tests passes without using `setMounted` in `onLoad`.

Some `GameWidget` tests I want a second opinion on, or ideas of how to make those tests better, because when setting mounted explicitly it kind of cheats on part of those tests.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #1351 

[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/flame-engine/flame/blob/main/CHANGELOG.md

### CODE REVIEW

File: packages/flame_test/lib/src/flame_test.dart [hunk 1]
```diff
@@ -89,9 +95,12 @@ class GameTester<T extends Game> {
     game.onGameResize(size);
 
     await game.onLoad();
+    game.onMount();
     game.update(0);
     if (game is FlameGame && makeReady) {
       await game.ready();
+      // ignore: invalid_use_of_visible_for_testing_member
```
Comment (luanpotter) [inline packages/flame_test/lib/src/flame_test.dart:102]: do we need these since this is a test file?

**Review by luanpotter — APPROVED** [review]
LGTM with one comment

File: packages/flame_test/lib/src/flame_test.dart (hunk 1 above)
Comment (spydon) [reply packages/flame_test/lib/src/flame_test.dart:102]: For some reason the analyzer doesn't recognise it as a test.

**Review by renancaraujo — APPROVED** [review]

File: packages/flame_test/lib/src/flame_test.dart [hunk 2]
```diff
@@ -158,6 +167,12 @@ class GameTester<T extends Game> {
           await _pump(gameWidget, tester);
           await tester.pump();
 
+          if (makeReady && game is FlameGame) {
+            // ignore: invalid_use_of_visible_for_testing_member
+            game.setMounted();
```
Comment (st-pasha) [inline packages/flame_test/lib/src/flame_test.dart:172]: This looks suspicious to me: if the `game` is being put into a `GameWidget`, which is pumped through a `tester`, then this should be no different than the "normal" use of `FlameGame`. In other words, `setMounted` should not be necessary here...

Which makes me wonder - have we checked that the examples are still working ok?

Comment (spydon) [reply packages/flame_test/lib/src/flame_test.dart:172]: Agree, which examples are you referring to?

Comment (st-pasha) [reply packages/flame_test/lib/src/flame_test.dart:172]: I just tried running `examples/lib/main.dart` from this branch, and immediately got an error:
```
Assertion failed: file:///flame/packages/flame/lib/src/components/core/component.dart:1024:14
child._parent!.isMounted
```

Comment (spydon) [reply packages/flame_test/lib/src/flame_test.dart:172]: Interesting, so somehow it isn't called in the order I expected then I guess, or not called at all... Any clue what could be wrong? I guess that would solve the sketchy widget tests too

Comment (spydon) [reply packages/flame_test/lib/src/flame_test.dart]: Now I'm doing `setMounted` explicitly from the `GameWidget` instead after `onMount`, do you think that is the correct way to do it?

File: packages/flame/lib/src/game/game_widget/game_widget.dart [hunk 3]
```diff
@@ -195,12 +195,16 @@ class _GameWidgetState<T extends Game> extends State<GameWidget<T>> {
...
+        assert(game.hasLayout);
+        final onLoad = game.onLoadFuture;
         if (onLoad != null) {
           await onLoad;
         }
-        currentGame.onMount();
+        game.onMount();
+        if (game is FlameGame) {
+          game.setMounted();
+        }
```
Comment (spydon) [inline packages/flame/lib/src/game/game_widget/game_widget.dart:207]: @st-pasha @renancaraujo is this the way to go, or do you have any other ideas?

File: packages/flame_test/lib/src/flame_test.dart (hunk 2 above)
Comment (spydon) [reply packages/flame_test/lib/src/flame_test.dart]: Moving the discussion here:
https://github.com/flame-engine/flame/pull/2246/files#r1062345184

File: packages/flame/lib/src/game/game_widget/game_widget.dart (hunk 3 above)
Comment (st-pasha) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:207]: I wanted to suggest to set this flag directly in `onMount()`, but then I'm not even sure what `onMount` even means for the `Game` class (if it's distinct from attaching to the widget tree). So, perhaps we could set this flag at the end of the `onLoad()`?

Frankly, I'm completely confused here.

Comment (spydon) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:207]: `onLoad` should only run once of the game is removed from the widget and added again, so that would not render the correct behaviour. And running it directly in `onMount` would mean that the user would need to make sure they always run `super.onMount` last to get the correct behaviour, so I think the current solution is better than that.

Comment (st-pasha) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:207]: We can go with the current approach for now, and then if we think of a better way in the future, we can always refactor.

File: packages/flame/test/events/flame_game_mixins/has_draggable_components_test.dart [hunk 4]
```diff
@@ -2,26 +2,28 @@ import 'package:flame/components.dart';
...
 import 'package:flame/game.dart';
+import 'package:flame_test/flame_test.dart';
 import 'package:flutter_test/flutter_test.dart';
 
 void main() {
+  final draggableTester = GameTester(_GameWithHasDraggableComponents.new);
+  final dualDraggableTester = GameTester(_GameWithDualDraggableComponents.new);
+
   group('HasDraggableComponents', () {
-    testWidgets(
```
Comment (st-pasha) [inline packages/flame/test/events/flame_game_mixins/has_draggable_components_test.dart:9]: I don't think these changes to the tests are actually needed. They don't reduce the boilerplate in any way, plus they make the tests weaker.

When a test runs through `testWidgets()`, I can see how the `game` instance is created, and then put inside a `GameWidget`, and that widget is pumped through the test framework. When there is a "helper" function involved, I'll start to worry that it performs some "sneaky" initialization of the `game` instance (as it did before), and the code wouldn't actually work if it was used by an actual user who has no access to `@internal` methods.

File: packages/flame/lib/src/game/game_widget/game_widget.dart (hunk 3 above)
Comment (st-pasha) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:207]: I see that `FlameGame` now calls `setMounted()` inside its `mount()` method -- so perhaps these lines are no longer needed?

File: packages/flame/lib/src/game/game_widget/game_widget.dart [hunk 5]
```diff
@@ -195,12 +195,16 @@ class _GameWidgetState<T extends Game> extends State<GameWidget<T>> {
...
-        assert(currentGame.hasLayout);
-        final onLoad = currentGame.onLoadFuture;
+        final game = currentGame;
+        assert(game.hasLayout);
+        final onLoad = game.onLoadFuture;
         if (onLoad != null) {
           await onLoad;
         }
-        currentGame.onMount();
+        game.onMount();
```
Comment (st-pasha) [inline packages/flame/lib/src/game/game_widget/game_widget.dart:204]: should this be `game.mount()` now?

Comment (spydon) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:204]: It should be indeed, why are the tests passing...

File: packages/flame/lib/src/game/game_widget/game_widget.dart (hunk 3 above)
Comment (spydon) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:207]: Missed removing that one, removed now.

File: packages/flame/lib/src/game/game_widget/game_widget.dart (hunk 5 above)
Comment (spydon) [reply packages/flame/lib/src/game/game_widget/game_widget.dart:204]: Since the other one was still there of course, fixed now.

File: packages/flame/test/events/flame_game_mixins/has_draggable_components_test.dart (hunk 4 above)
Comment (spydon) [reply packages/flame/test/events/flame_game_mixins/has_draggable_components_test.dart:9]: Yeah, since there is no need for the initialization hack anymore I can revert these.
But it would be nice to be consistent with how we do the tests, and now `testGameWidget` is used on some places and `testWidgets` is used on some.

File: packages/flame/lib/src/game/game_widget/game_widget.dart (hunk 3 above)
Comment (spydon) [reply packages/flame/lib/src/game/game_widget/game_widget.dart]: @st-pasha everything should be updated now, can you have another look? :)

**Review by st-pasha — APPROVED** [review]
Looks all good!
