### PR TITLE
fix: Auto-resize `SpriteComponent` on sprite change

### LINKED ISSUE #2419: `SpriteComponent` doesn't auto-resize
# Current bug behavior

If sprite of a `SpriteComponent` is set or updated after construction of the component, the size of the component does not update.

# Expected behavior

Ideally the size of `SpriteComponent` should be automatically updated by default. Additionally a an option can be provided to turn this resizing off by setting a flag in `SpriteComponent`.

# Steps to reproduce

Setting up a sprite component like this will make it render with zero size:
```dart
final spriteComponent = SpriteComponent();
spriteComponent.sprite = await Sprite.load('arrow_up.png');
add(spriteComponent);
```

# Flutter doctor output

NA

# More environment information

Flame version: 1.6.0
Platform affected: All

# Log information

```
Enter log information in this code block
```
NA

# More information

I can work on this.

### PR DESCRIPTION
**Pull request by ufrshubham**
# Description

This PR adds an `autoResize` parameter to `SpriteComponent` using which users will be able to control if the component should auto-resize on sprite change to match the sprite's `srcSize`. Some important design decisions about `autoResize`:

- It is mutually exclusive with `size` while construction: This means, if `size` is non-null while construction of `SpriteComponent`, `autoResize` cannot be true. This allows use-cases where one might want to render a sprite at a different size than its original size. If an user is setting the size explicitly, we can leave it up to them to handle resizing in such cases. 

- It is optional: If an user does not set this parameter while construction, it will be auto-populated depending upon if a `size` is provided or not.

## Checklist

- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #2419

### CODE REVIEW

File: packages/flame/lib/src/components/sprite_component.dart [hunk 1]
```diff
@@ -15,12 +15,46 @@ export '../sprite.dart';
...
+
+  /// Returns current value of auto resize flag.
+  bool get autoResize => _autoResize;
+
+  /// Sets the given value of autoResize flag. Will update the [size]
+  /// to fit srcSize of [sprite] if set to  true.
+  set autoResize(bool value) {
+    _autoResize = value;
+    if (value) {
+      size.setFrom(sprite?.srcSize ?? Vector2.zero());
```
Comment (spydon) [inline packages/flame/lib/src/components/sprite_component.dart:30]: It should probably do a null check outside here instead and use `setZero` if it's null so that no new vector is created

Comment (spydon) [reply packages/flame/lib/src/components/sprite_component.dart:30]: Ah, just like you do further down

File: packages/flame/lib/src/components/sprite_component.dart [hunk 2]
```diff
@@ -30,9 +64,14 @@ class SpriteComponent extends PositionComponent
     super.anchor,
     super.children,
     super.priority,
-  }) : super(
-          size: size ?? sprite?.srcSize,
-        ) {
+  })  : assert(
+          (size == null && (autoResize ?? true)) ||
+              (size != null && !(autoResize ?? false)),
```
Comment (spydon) [inline packages/flame/lib/src/components/sprite_component.dart:69]:
```suggestion
          (size == null && (autoResize ?? true)) ||
              (size != null && !(autoResize ?? false)),
```
Hmm, shouldn't this be possible to write as a single XOR expression?

**Review by spydon — APPROVED** [review]
Lgtm, just some small nits :)

File: packages/flame/lib/src/components/sprite_component.dart (hunk 1 above)
Comment (ufrshubham) [reply packages/flame/lib/src/components/sprite_component.dart]: Done.

File: packages/flame/lib/src/components/sprite_component.dart (hunk 2 above)
Comment (ufrshubham) [reply packages/flame/lib/src/components/sprite_component.dart]: Simplified as suggested.

**Review by luanpotter — APPROVED** [review]
Nice!

File: packages/flame/lib/src/components/sprite_component.dart [hunk 3]
```diff
@@ -15,12 +15,50 @@ export '../sprite.dart';
...
+
+  /// Sets the given value of autoResize flag. Will update the [size]
+  /// to fit srcSize of [sprite] if set to  true.
+  set autoResize(bool value) {
+    _autoResize = value;
+    if (value) {
+      if (_sprite != null) {
+        size.setFrom(_sprite!.srcSize);
+      } else {
+        size.setZero();
```
Comment (erickzanardo) [inline packages/flame/lib/src/components/sprite_component.dart:33]: Shouldn't we just do nothing when it is false? I would expect the previous size to still be there if setting auto size to false

File: packages/flame/lib/src/components/sprite_component.dart [hunk 4]
```diff
@@ -15,12 +15,50 @@ export '../sprite.dart';
...
+  /// Sets the given sprite as the new [sprite] of this component.
+  /// Will update the size if [autoResize] is set to true.
+  set sprite(Sprite? value) {
+    _sprite = value;
+
+    if (_autoResize) {
+      if (value != null) {
+        size.setFrom(value.srcSize);
+      } else {
+        size.setZero();
```
Comment (erickzanardo) [inline packages/flame/lib/src/components/sprite_component.dart:53]: Same suggestions

**Review by erickzanardo — COMMENTED** [review]
Awesome idea! Addded a couple of comments before approving

File: packages/flame/lib/src/components/sprite_component.dart (hunk 3 above)
Comment (ufrshubham) [reply packages/flame/lib/src/components/sprite_component.dart:33]: Wouldn't that break the contract of this setter? If `autoResize` is on and there is no sprite, wouldn't you expect the size of component to be zero as well?

Comment (erickzanardo) [reply packages/flame/lib/src/components/sprite_component.dart:33]: Ah, got ya, you are only setting the zero when there is no sprite. That makes sense!!!

**Review by erickzanardo — APPROVED** [review]
