### PR TITLE
fix: Make CollisionProspect's a, b have unordered equality

### LINKED ISSUE #1478: Collision callbacks start and end are called in the same tick with many added hitboxes
# Current bug behaviour
When two hitboxs has same size and overlaps perfectly,
`onCollisionStart` and `onCollisionEnd` callback called alternately and indefinitely even though there is no position changed. 

# Expected behaviour
I don't know actually but at least current behavior is weired...

# Steps to reproduce
1. Create Two components that has hitbox
2. Set hitbox size as same as each other

# Flutter doctor output
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale ko-KR)
    • Flutter version 2.10.3 at /Users/lafity101/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/lafity101/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone (mobile) • DEVICE_ID • ios            • iOS 15.1 19B74
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

# More environment information

* Flame version: `main` branch

# Log information

```dart
[ +31 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ +33 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ +31 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ +16 ms] flutter: start collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
[ ] flutter: end collision other: [2448.0,1296.0], size: [32.0,32.0] // me: center: [2448.0,1296.0], size: [32.0,52.0]
... you can see this at the following video
```

https://user-images.githubusercontent.com/38072762/159412816-5b081754-77a1-40f5-aee3-76358794aaab.mov

### PR DESCRIPTION
**Pull request by Hwan-seok**
# Description
See [this comment](https://github.com/flame-engine/flame/issues/1478#issuecomment-1091453143)

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Fixes #1478 

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by Hwan-seok** [comment]
@spydon 
Should I remove or clean up the reproducing test code?

File: packages/flame/test/collisions/collision_callback_test.dart [hunk 1]
```diff
@@ -393,12 +393,12 @@ void main() {
...
-          // the same collision in the same tick.
-          print('$i: ${player.position}');
-        }
-        //expect(player.endCounter, 0); // <---- this is the point that fails test
+        // if (player.endCounter != 0) {
+        //   // Should not get in here since it can't both start and end
+        //   // the same collision in the same tick.
+        //   print('$i: ${player.position}');
+        // }
+        expect(player.endCounter, 0); // <---- this is the point that fails test
```
Comment (spydon) [inline packages/flame/test/collisions/collision_callback_test.dart:401]:
```suggestion
        expect(player.endCounter, 0);
```

**Review by spydon — APPROVED** [review]
Well done! Such a simple solution to such an annoying bug. 😄
