### PR TITLE
fix: ButtonComponent behavior when the engine is paused

### LINKED ISSUE #1723: Null exception while removing overlay and resuming engine
# Current bug behaviour
While trying to remove an overlay and resume engine, a null exception is raised from `Component._remove()`.

# Expected behavior
Since it was working in Flame 1.1.1 without any exceptions, that is the expected behavior.

# Steps to reproduce
Here is a simple code which should be enough to reproduce this bug. Tapping on the `CircleComponent` pauses the game and adds an overlay called `PauseMenu`. On pressing the resume button from `PauseMenu`, the game is resumed and overlay is removed.
```dart
final game = MyGame();

void main() {
  runApp(
    GameWidget<MyGame>(
      game: game,
      overlayBuilderMap: {
        PauseMenu.id: (context, game) => PauseMenu(gameRef: game),
      },
    ),
  );
}

class MyGame extends FlameGame with HasTappables {
  @override
  Future<void>? onLoad() {
    add(
      ButtonComponent(
        button: CircleComponent(radius: 40),
        position: size / 2,
        anchor: Anchor.center,
        onPressed: () {
          pauseEngine();
          overlays.add(PauseMenu.id);
        },
      ),
    );
    return super.onLoad();
  }
}

class PauseMenu extends StatelessWidget {
  static const id = 'Pause';
  final MyGame gameRef;
  const PauseMenu({Key? key, required this.gameRef}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: OutlinedButton(
        onPressed: () {
          gameRef.overlays.remove(PauseMenu.id);
          gameRef.resumeEngine();
        },
        child: const Text('Resume'),
      ),
    );
  }
}
```

# Flutter doctor output

```
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.708], locale en-US)
    • Flutter version 3.0.2 at C:\apps\android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\apps\android
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\apps\android
    • ANDROID_SDK_ROOT = C:\apps\android\cmdline-tools\tools
    • Java binary at: C:\apps\openjdk-11.0.2_windows-x64_bin\jdk-11.0.2\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.68.0)
    • VS Code at C:\Users\Ryuzaki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.708]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.30

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

# More environment information

# Log information

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      Component._remove
#1      _LifecycleManager._processAdoptionQueue
#2      _LifecycleManager.processQueues
#3      Component.updateTree
#4      FlameGame.updateTree.<anonymous closure>
#5      IterableMixin.forEach (dart:collection/iterable.dart:45:35)
#6      FlameGame.updateTree
#7      FlameGame.update
#8      GameRenderBox.gameLoopCallback
#9      GameLoop._tick
#10     Ticker._tick
#11     SchedulerBinding._invokeFrameCallback
#12     SchedulerBinding.handleBeginFrame.<anonymous closure>
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#14     SchedulerBinding.handleBeginFrame
#15     SchedulerBinding._handleBeginFrame
#19     _invoke1 (dart:ui/hooks.dart:170:10)
#20     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
#21     _beginFrame (dart:ui/hooks.dart:104:31)
(elided 3 frames from dart:async)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback
#3      Ticker.scheduleTick
#4      Ticker.start
#5      GameLoop.start
#6      Game.resumeEngine
#7      PauseMenu.build.<anonymous closure>
#8      _InkResponseState._handleTap
#9      GestureRecognizer.invokeCallback
#10     TapGestureRecognizer.handleTapUp
#11     BaseTapGestureRecognizer._checkUp
#12     BaseTapGestureRecognizer.handlePrimaryPointer
#13     PrimaryPointerGestureRecognizer.handleEvent
#14     PointerRouter._dispatch
#15     PointerRouter._dispatchEventToRoutes.<anonymous closure>
#16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#17     PointerRouter._dispatchEventToRoutes
#18     PointerRouter.route
#19     GestureBinding.handleEvent
#20     GestureBinding.dispatchEvent
#21     RendererBinding.dispatchEvent
#22     GestureBinding._handlePointerEventImmediately
#23     GestureBinding.handlePointerEvent
#24     GestureBinding._flushPointerEventQueue
#25     GestureBinding._handlePointerDataPacket
#29     _invoke1 (dart:ui/hooks.dart:170:10)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _FrameCallbackEntry and dart:async)
════════════════════════════════════════════════════════════════════════════════

```

# More information
- I've verified that this was working in Flame 1.1.1. Seems to have regressed since 1.2.0 (maybe because of the changes to overlay system).
- Also verified that this fail on `main` as well (latest commit was f08f8e12f5322c7bea1491908f06b350e13c14b7).

### PR DESCRIPTION
**Pull request by st-pasha**
# Description

- In `Component`, we will now avoid adoption queue when setting parent to the same as the current;
- The `ButtonComponent` avoids swapping `button` and `buttonDown` components if `buttonDown` is null;

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [-] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [-] I have updated/added relevant examples in `examples`.

## Breaking Change

- [-] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1723

[issue database]: https://github.com/flame-engine/flame/issues
[Contributor Guide]: https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md
[Flame Style Guide]: https://github.com/flame-engine/flame/blob/main/STYLEGUIDE.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

File: packages/flame/lib/src/components/input/button_component.dart [hunk 1]
```diff
@@ -45,17 +45,18 @@ class ButtonComponent extends PositionComponent with Tappable {
...
     }
   }
 
   @override
   @mustCallSuper
   bool onTapDown(TapDownInfo info) {
-    button?.removeFromParent();
-    buttonDown?.changeParent(this);
+    if (buttonDown != null) {
+      button!.parent = null;
```
Comment (spydon) [inline packages/flame/lib/src/components/input/button_component.dart:57]: I think it looks nicer to avoid setting the parent to null explicitly, and only let the method handle the remove method handle that.

Comment (st-pasha) [reply packages/flame/lib/src/components/input/button_component.dart]: ok

**Review by spydon — APPROVED** [review]

**Review by luanpotter — APPROVED** [review]
