### PR TITLE
Add TextBoxConfig options and fix TextBoxComponent bugs

### LINKED ISSUE #532: TextBoxComponent exception
## Description

Example for [text](https://github.com/flame-engine/flame/blob/a3fa58377681cb3505bdb51e5af6729cdf4b8f77/doc/examples/text/lib/main.dart) in documentation not work.

StackTrace:

```
E/flutter (32743): Tried calling: x
E/flutter (32743): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (32743): #1      Vector2Extension.toRect (package:flame/extensions/vector2.dart:23:40)
E/flutter (32743): #2      TextBoxComponent._redrawCache (package:flame/components/text_box_component.dart:151:48)
E/flutter (32743): #3      TextBoxComponent.redrawLater (package:flame/components/text_box_component.dart:179:20)
E/flutter (32743): #4      new TextBoxComponent (package:flame/components/text_box_component.dart:77:5)
E/flutter (32743): #5      new MyTextBox (package:abaron/main.dart:23:9)
E/flutter (32743): #6      new MyGame (package:abaron/main.dart:53:9)
E/flutter (32743): #7      main (package:abaron/main.dart:15:10)
```

## Development environment

Flame version:

1.0.0-rc2

Flutter doctor:

```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H15 x86_64, locale ru)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1.1)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x] Android :android:

## Minimal reproducible code (Required for bugs)

Cropped example code:

```dart
import 'dart:ui';

import 'package:flame/anchor.dart';
import 'package:flame/components/text_box_component.dart';
import 'package:flame/extensions/vector2.dart';
import 'package:flame/flame.dart';
import 'package:flame/game.dart';
import 'package:flame/palette.dart';
import 'package:flame/text_config.dart';
import 'package:flutter/material.dart';

void main() async {
  final Vector2 size = await Flame.util.initialDimensions();
  runApp(MyGame(size).widget);
}

TextConfig regular = TextConfig(color: BasicPalette.white.color);
TextConfig tiny = regular.withFontSize(12.0);

class MyTextBox extends TextBoxComponent {
  MyTextBox(String text)
      : super(text, config: tiny, boxConfig: TextBoxConfig(timePerChar: 0.05));

  @override
  void drawBackground(Canvas c) {
    final Rect rect = Rect.fromLTWH(0, 0, width, height);
    c.drawRect(rect, Paint()..color = const Color(0xFFFF00FF));
    c.drawRect(
        rect.deflate(boxConfig.margin),
        Paint()
          ..color = BasicPalette.black.color
          ..style = PaintingStyle.stroke);
  }
}

class MyGame extends BaseGame {
  MyGame(Vector2 screenSize) {
    size = screenSize;

    add(MyTextBox(
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum.',
    )
      ..anchor = Anchor.bottomLeft
      ..y = size.y);
  }
}
```

### PR DESCRIPTION
**Pull request by spydon**
# Description

* The TextBoxComponent wasn't rendering at all in v1.0.0 so that is fixed.
* Adds full margin options
* Adds option whether the box should be growing or not

Fixes #532 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `v1.0.0`
- [x] This PR is targeted to merge into `v1.0.0` (not `master` or `develop`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] I have made corresponding changes to the documentation
- [x] I have added examples for new features in `doc/examples`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

File: doc/examples/text/lib/main.dart [hunk 1]
```diff
@@ -20,16 +20,27 @@ TextConfig tiny = regular.withFontSize(12.0);
...
+            margins: const EdgeInsets.symmetric(horizontal: 10, vertical: 15),
+          ),
+        );
 
   @override
   void drawBackground(Canvas c) {
     final Rect rect = Rect.fromLTWH(0, 0, width, height);
     c.drawRect(rect, Paint()..color = const Color(0xFFFF00FF));
+    final margin = boxConfig.margins;
+    final Rect innerRect = Rect.fromLTWH(margin.left, margin.top,
```
Comment (luanpotter) [inline doc/examples/text/lib/main.dart:38]: single line or one per line

File: lib/components/text_box_component.dart [hunk 2]
```diff
@@ -103,39 +105,43 @@ class TextBoxComponent extends PositionComponent with Resizable {
...
-    return _lines.sublist(0, _currentLine + 1).map((line) {
-      final int charCount =
-          (i < _currentLine) ? line.length : (_currentChar - totalCharCount);
-      totalCharCount += line.length;
-      i++;
-      return getLineWidth(line, charCount);
-    }).reduce(math.max);
+  @override
+  double get width {
+    if (_boxConfig.growingBox) {
```
Comment (luanpotter) [inline lib/components/text_box_component.dart:119]: I think we should cache this? I expect that component.width to be O(0)

File: lib/components/text_box_component.dart [hunk 3]
```diff
@@ -59,22 +61,22 @@ class TextBoxComponent extends PositionComponent with Resizable {
     text.split(' ').forEach((word) {
       final String possibleLine =
           _lines.isEmpty ? word : _lines.last + ' ' + word;
-      final widgets.TextPainter p = config.toTextPainter(possibleLine);
-      _lineHeight ??= p.height;
-      if (p.width <= _boxConfig.maxWidth - 2 * _boxConfig.margin) {
+      final TextPainter painter = config.toTextPainter(possibleLine);
```
Comment (luanpotter) [inline lib/components/text_box_component.dart:64]: we can omit types for local variables

Comment (luanpotter) [reply lib/components/text_box_component.dart:64]: `_lines.last + ' ' + word` can be done with string templates?

File: lib/components/text_box_component.dart (hunk 2 above)
Comment (spydon) [reply lib/components/text_box_component.dart:119]: It depends if it is a growing box or not, but yeah, it can be cacheable even if it is not. I'll look into it.

**Review by erickzanardo — APPROVED** [review]
LGTM once Luan's comments are addressed

**Review by renancaraujo — APPROVED** [review]
