### PR TITLE
Fix children update and rendering

### LINKED ISSUE #562: AnimationComponent not work as child of PositionComponent
## Description

If use AnimatedComponent as child of PositionComponent - animation not work.

## Development environment

Flame version:

develop branch

Flutter doctor:

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale ru)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1.1)
[✓] Chrome - develop for the web[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)

```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x] Android :android:
 - [x] iOS :apple:
 - [x] Web :browser:

## Minimal reproducible code (Required for bugs)

```dart
import 'dart:ui';

import 'package:flame/components/mixins/has_game_ref.dart';
import 'package:flame/components/position_component.dart';
import 'package:flame/components/sprite_animation_component.dart';
import 'package:flame/extensions/vector2.dart';
import 'package:flame/flame.dart';
import 'package:flame/game.dart';
import 'package:flame/gestures.dart';
import 'package:flame/sprite_animation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart' hide Image;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final Vector2 size = await Flame.util.initialDimensions();
  final game = MyGame(size);
  runApp(
    GameWidget(
      game: game,
    ),
  );
}

class TestComponent extends PositionComponent with HasGameRef<MyGame> {
  TestComponent(Vector2 size) {
    this.size = size;
    debugMode = true;
  }

  void addAnimation(Vector2 position) {
    final size = Vector2(291, 178);

    final animationComponent = SpriteAnimationComponent.fromFrameData(
      size,
      gameRef.images.fromCache('creature.png'),
      SpriteAnimationData.sequenced(
        amount: 18,
        amountPerRow: 10,
        textureSize: size,
        stepTime: 0.15,
        loop: false,
      ),
      removeOnFinish: true,
    );

    animationComponent.position = position;
    animationComponent.position = animationComponent.position - size / 2;
    addChild(animationComponent);
  }
}

class MyGame extends BaseGame with TapDetector {
  late Image chopper;
  late Image creature;
  late SpriteAnimation animation;
  late TestComponent test;

  @override
  Future<void> onLoad() async {
    chopper = await images.load('chopper.png');
    creature = await images.load('creature.png');

    animation = SpriteAnimation.fromFrameData(
      chopper,
      SpriteAnimationData.sequenced(
        amount: 4,
        textureSize: Vector2.all(48),
        stepTime: 0.15,
        loop: true,
      ),
    );

    final spriteSize = Vector2.all(100.0);
    final animationComponent2 = SpriteAnimationComponent(spriteSize, animation);
    animationComponent2.x = size.x / 2 - spriteSize.x;
    animationComponent2.y = spriteSize.y;

    final reversedAnimationComponent = SpriteAnimationComponent(
      spriteSize,
      animation.reversed(),
    );
    reversedAnimationComponent.x = size.x / 2;
    reversedAnimationComponent.y = spriteSize.y;

    test = TestComponent(this.size);

    test.addChild(animationComponent2);
    test.addChild(reversedAnimationComponent);

    add(test);
  }

  @override
  void onTapDown(TapDownDetails evt) {
    test.addAnimation(Vector2(evt.globalPosition.dx, evt.globalPosition.dy));
  }

  MyGame(Vector2 screenSize) {
    size.setFrom(screenSize);
  }
}
```

### PR DESCRIPTION
**Pull request by spydon**
# Description

The rendering and update of the children was lost in the last refactoring.

Fixes #562 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

If something is unclear, please submit the PR anyways and ask about what you thought was unclear.

- [x] This branch is based on `develop`
- [x] This PR is targeted to merge into `develop` (not `master` or `develop`)
- [x] I have added an entry under `[next]` in `CHANGELOG.md`
- [x] I have formatted my code with `flutter format`
- [x] The continuous integration (CI) is passing

### CODE REVIEW

File: test/components/composed_component_test.dart [hunk 1]
```diff
@@ -38,15 +52,29 @@ void main() {
...
+    test('updates and renders children', () {
+      final MyGame game = MyGame();
+      final MyTap child = MyTap();
+      final MyComposed wrapper = MyComposed();
+
+      wrapper.addChild(child);
+      game.add(wrapper);
+      game.update(0.0);
+
+      //expect(child.rendered, true);
```
Comment (renancaraujo) [inline test/components/composed_component_test.dart:76]: Commentedf code.

**Review by renancaraujo — APPROVED** [review]

File: test/components/composed_component_test.dart (hunk 1 above)
Comment (spydon) [reply test/components/composed_component_test.dart]: Good catch, fixed now!

File: test/util/mock_canvas.dart [hunk 2]
```diff
@@ -0,0 +1,28 @@
+import 'dart:ui';
+
+import 'package:test/fake.dart';
+
+class MockCanvas extends Fake implements Canvas {
```
Comment (erickzanardo) [inline test/util/mock_canvas.dart:5]: I wonder if we could start using a mock (like mockito) library instead of doing that manually, don't need to change for this PR, but something to think about on the next PRs

**Review by erickzanardo — APPROVED** [review]

File: test/util/mock_canvas.dart (hunk 2 above)
Comment (spydon) [reply test/util/mock_canvas.dart:5]: Yeah that could be a good idea!
